/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/dns/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDomainRegistrationNameserverses implements DomainRegistrationNameserversInterface
type FakeDomainRegistrationNameserverses struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var domainregistrationnameserversesResource = schema.GroupVersionResource{Group: "dns.ibm.kubeform.com", Version: "v1alpha1", Resource: "domainregistrationnameserverses"}

var domainregistrationnameserversesKind = schema.GroupVersionKind{Group: "dns.ibm.kubeform.com", Version: "v1alpha1", Kind: "DomainRegistrationNameservers"}

// Get takes name of the domainRegistrationNameservers, and returns the corresponding domainRegistrationNameservers object, and an error if there is any.
func (c *FakeDomainRegistrationNameserverses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainRegistrationNameservers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(domainregistrationnameserversesResource, c.ns, name), &v1alpha1.DomainRegistrationNameservers{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRegistrationNameservers), err
}

// List takes label and field selectors, and returns the list of DomainRegistrationNameserverses that match those selectors.
func (c *FakeDomainRegistrationNameserverses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainRegistrationNameserversList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(domainregistrationnameserversesResource, domainregistrationnameserversesKind, c.ns, opts), &v1alpha1.DomainRegistrationNameserversList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DomainRegistrationNameserversList{ListMeta: obj.(*v1alpha1.DomainRegistrationNameserversList).ListMeta}
	for _, item := range obj.(*v1alpha1.DomainRegistrationNameserversList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested domainRegistrationNameserverses.
func (c *FakeDomainRegistrationNameserverses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(domainregistrationnameserversesResource, c.ns, opts))

}

// Create takes the representation of a domainRegistrationNameservers and creates it.  Returns the server's representation of the domainRegistrationNameservers, and an error, if there is any.
func (c *FakeDomainRegistrationNameserverses) Create(ctx context.Context, domainRegistrationNameservers *v1alpha1.DomainRegistrationNameservers, opts v1.CreateOptions) (result *v1alpha1.DomainRegistrationNameservers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(domainregistrationnameserversesResource, c.ns, domainRegistrationNameservers), &v1alpha1.DomainRegistrationNameservers{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRegistrationNameservers), err
}

// Update takes the representation of a domainRegistrationNameservers and updates it. Returns the server's representation of the domainRegistrationNameservers, and an error, if there is any.
func (c *FakeDomainRegistrationNameserverses) Update(ctx context.Context, domainRegistrationNameservers *v1alpha1.DomainRegistrationNameservers, opts v1.UpdateOptions) (result *v1alpha1.DomainRegistrationNameservers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(domainregistrationnameserversesResource, c.ns, domainRegistrationNameservers), &v1alpha1.DomainRegistrationNameservers{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRegistrationNameservers), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDomainRegistrationNameserverses) UpdateStatus(ctx context.Context, domainRegistrationNameservers *v1alpha1.DomainRegistrationNameservers, opts v1.UpdateOptions) (*v1alpha1.DomainRegistrationNameservers, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(domainregistrationnameserversesResource, "status", c.ns, domainRegistrationNameservers), &v1alpha1.DomainRegistrationNameservers{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRegistrationNameservers), err
}

// Delete takes name of the domainRegistrationNameservers and deletes it. Returns an error if one occurs.
func (c *FakeDomainRegistrationNameserverses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(domainregistrationnameserversesResource, c.ns, name), &v1alpha1.DomainRegistrationNameservers{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDomainRegistrationNameserverses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(domainregistrationnameserversesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DomainRegistrationNameserversList{})
	return err
}

// Patch applies the patch and returns the patched domainRegistrationNameservers.
func (c *FakeDomainRegistrationNameserverses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainRegistrationNameservers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(domainregistrationnameserversesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DomainRegistrationNameservers{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRegistrationNameservers), err
}
