/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/app/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigFeatures implements ConfigFeatureInterface
type FakeConfigFeatures struct {
	Fake *FakeAppV1alpha1
	ns   string
}

var configfeaturesResource = schema.GroupVersionResource{Group: "app.ibm.kubeform.com", Version: "v1alpha1", Resource: "configfeatures"}

var configfeaturesKind = schema.GroupVersionKind{Group: "app.ibm.kubeform.com", Version: "v1alpha1", Kind: "ConfigFeature"}

// Get takes name of the configFeature, and returns the corresponding configFeature object, and an error if there is any.
func (c *FakeConfigFeatures) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConfigFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(configfeaturesResource, c.ns, name), &v1alpha1.ConfigFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigFeature), err
}

// List takes label and field selectors, and returns the list of ConfigFeatures that match those selectors.
func (c *FakeConfigFeatures) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConfigFeatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(configfeaturesResource, configfeaturesKind, c.ns, opts), &v1alpha1.ConfigFeatureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConfigFeatureList{ListMeta: obj.(*v1alpha1.ConfigFeatureList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConfigFeatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configFeatures.
func (c *FakeConfigFeatures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(configfeaturesResource, c.ns, opts))

}

// Create takes the representation of a configFeature and creates it.  Returns the server's representation of the configFeature, and an error, if there is any.
func (c *FakeConfigFeatures) Create(ctx context.Context, configFeature *v1alpha1.ConfigFeature, opts v1.CreateOptions) (result *v1alpha1.ConfigFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(configfeaturesResource, c.ns, configFeature), &v1alpha1.ConfigFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigFeature), err
}

// Update takes the representation of a configFeature and updates it. Returns the server's representation of the configFeature, and an error, if there is any.
func (c *FakeConfigFeatures) Update(ctx context.Context, configFeature *v1alpha1.ConfigFeature, opts v1.UpdateOptions) (result *v1alpha1.ConfigFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(configfeaturesResource, c.ns, configFeature), &v1alpha1.ConfigFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigFeature), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigFeatures) UpdateStatus(ctx context.Context, configFeature *v1alpha1.ConfigFeature, opts v1.UpdateOptions) (*v1alpha1.ConfigFeature, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(configfeaturesResource, "status", c.ns, configFeature), &v1alpha1.ConfigFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigFeature), err
}

// Delete takes name of the configFeature and deletes it. Returns an error if one occurs.
func (c *FakeConfigFeatures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(configfeaturesResource, c.ns, name), &v1alpha1.ConfigFeature{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigFeatures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(configfeaturesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConfigFeatureList{})
	return err
}

// Patch applies the patch and returns the patched configFeature.
func (c *FakeConfigFeatures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConfigFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(configfeaturesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConfigFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigFeature), err
}
