/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubeform.dev/provider-ibm-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AccessGroups returns a AccessGroupInformer.
	AccessGroups() AccessGroupInformer
	// AccessGroupDynamicRules returns a AccessGroupDynamicRuleInformer.
	AccessGroupDynamicRules() AccessGroupDynamicRuleInformer
	// AccessGroupMemberses returns a AccessGroupMembersInformer.
	AccessGroupMemberses() AccessGroupMembersInformer
	// AccessGroupPolicies returns a AccessGroupPolicyInformer.
	AccessGroupPolicies() AccessGroupPolicyInformer
	// AccountSettingses returns a AccountSettingsInformer.
	AccountSettingses() AccountSettingsInformer
	// ApiKeys returns a ApiKeyInformer.
	ApiKeys() ApiKeyInformer
	// AuthorizationPolicies returns a AuthorizationPolicyInformer.
	AuthorizationPolicies() AuthorizationPolicyInformer
	// AuthorizationPolicyDetaches returns a AuthorizationPolicyDetachInformer.
	AuthorizationPolicyDetaches() AuthorizationPolicyDetachInformer
	// CustomRoles returns a CustomRoleInformer.
	CustomRoles() CustomRoleInformer
	// ServiceAPIKeys returns a ServiceAPIKeyInformer.
	ServiceAPIKeys() ServiceAPIKeyInformer
	// ServiceIDs returns a ServiceIDInformer.
	ServiceIDs() ServiceIDInformer
	// ServicePolicies returns a ServicePolicyInformer.
	ServicePolicies() ServicePolicyInformer
	// UserInvites returns a UserInviteInformer.
	UserInvites() UserInviteInformer
	// UserPolicies returns a UserPolicyInformer.
	UserPolicies() UserPolicyInformer
	// UserSettingses returns a UserSettingsInformer.
	UserSettingses() UserSettingsInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AccessGroups returns a AccessGroupInformer.
func (v *version) AccessGroups() AccessGroupInformer {
	return &accessGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AccessGroupDynamicRules returns a AccessGroupDynamicRuleInformer.
func (v *version) AccessGroupDynamicRules() AccessGroupDynamicRuleInformer {
	return &accessGroupDynamicRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AccessGroupMemberses returns a AccessGroupMembersInformer.
func (v *version) AccessGroupMemberses() AccessGroupMembersInformer {
	return &accessGroupMembersInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AccessGroupPolicies returns a AccessGroupPolicyInformer.
func (v *version) AccessGroupPolicies() AccessGroupPolicyInformer {
	return &accessGroupPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AccountSettingses returns a AccountSettingsInformer.
func (v *version) AccountSettingses() AccountSettingsInformer {
	return &accountSettingsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ApiKeys returns a ApiKeyInformer.
func (v *version) ApiKeys() ApiKeyInformer {
	return &apiKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AuthorizationPolicies returns a AuthorizationPolicyInformer.
func (v *version) AuthorizationPolicies() AuthorizationPolicyInformer {
	return &authorizationPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AuthorizationPolicyDetaches returns a AuthorizationPolicyDetachInformer.
func (v *version) AuthorizationPolicyDetaches() AuthorizationPolicyDetachInformer {
	return &authorizationPolicyDetachInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CustomRoles returns a CustomRoleInformer.
func (v *version) CustomRoles() CustomRoleInformer {
	return &customRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServiceAPIKeys returns a ServiceAPIKeyInformer.
func (v *version) ServiceAPIKeys() ServiceAPIKeyInformer {
	return &serviceAPIKeyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServiceIDs returns a ServiceIDInformer.
func (v *version) ServiceIDs() ServiceIDInformer {
	return &serviceIDInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServicePolicies returns a ServicePolicyInformer.
func (v *version) ServicePolicies() ServicePolicyInformer {
	return &servicePolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UserInvites returns a UserInviteInformer.
func (v *version) UserInvites() UserInviteInformer {
	return &userInviteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UserPolicies returns a UserPolicyInformer.
func (v *version) UserPolicies() UserPolicyInformer {
	return &userPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UserSettingses returns a UserSettingsInformer.
func (v *version) UserSettingses() UserSettingsInformer {
	return &userSettingsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
