/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvisioningHooks implements ProvisioningHookInterface
type FakeProvisioningHooks struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var provisioninghooksResource = schema.GroupVersionResource{Group: "compute.ibm.kubeform.com", Version: "v1alpha1", Resource: "provisioninghooks"}

var provisioninghooksKind = schema.GroupVersionKind{Group: "compute.ibm.kubeform.com", Version: "v1alpha1", Kind: "ProvisioningHook"}

// Get takes name of the provisioningHook, and returns the corresponding provisioningHook object, and an error if there is any.
func (c *FakeProvisioningHooks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProvisioningHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(provisioninghooksResource, c.ns, name), &v1alpha1.ProvisioningHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisioningHook), err
}

// List takes label and field selectors, and returns the list of ProvisioningHooks that match those selectors.
func (c *FakeProvisioningHooks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProvisioningHookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(provisioninghooksResource, provisioninghooksKind, c.ns, opts), &v1alpha1.ProvisioningHookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProvisioningHookList{ListMeta: obj.(*v1alpha1.ProvisioningHookList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProvisioningHookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested provisioningHooks.
func (c *FakeProvisioningHooks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(provisioninghooksResource, c.ns, opts))

}

// Create takes the representation of a provisioningHook and creates it.  Returns the server's representation of the provisioningHook, and an error, if there is any.
func (c *FakeProvisioningHooks) Create(ctx context.Context, provisioningHook *v1alpha1.ProvisioningHook, opts v1.CreateOptions) (result *v1alpha1.ProvisioningHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(provisioninghooksResource, c.ns, provisioningHook), &v1alpha1.ProvisioningHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisioningHook), err
}

// Update takes the representation of a provisioningHook and updates it. Returns the server's representation of the provisioningHook, and an error, if there is any.
func (c *FakeProvisioningHooks) Update(ctx context.Context, provisioningHook *v1alpha1.ProvisioningHook, opts v1.UpdateOptions) (result *v1alpha1.ProvisioningHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(provisioninghooksResource, c.ns, provisioningHook), &v1alpha1.ProvisioningHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisioningHook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvisioningHooks) UpdateStatus(ctx context.Context, provisioningHook *v1alpha1.ProvisioningHook, opts v1.UpdateOptions) (*v1alpha1.ProvisioningHook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(provisioninghooksResource, "status", c.ns, provisioningHook), &v1alpha1.ProvisioningHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisioningHook), err
}

// Delete takes name of the provisioningHook and deletes it. Returns an error if one occurs.
func (c *FakeProvisioningHooks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(provisioninghooksResource, c.ns, name), &v1alpha1.ProvisioningHook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvisioningHooks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(provisioninghooksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProvisioningHookList{})
	return err
}

// Patch applies the patch and returns the patched provisioningHook.
func (c *FakeProvisioningHooks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProvisioningHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(provisioninghooksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProvisioningHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisioningHook), err
}
