/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/kms/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKeyRingses implements KeyRingsInterface
type FakeKeyRingses struct {
	Fake *FakeKmsV1alpha1
	ns   string
}

var keyringsesResource = schema.GroupVersionResource{Group: "kms.ibm.kubeform.com", Version: "v1alpha1", Resource: "keyringses"}

var keyringsesKind = schema.GroupVersionKind{Group: "kms.ibm.kubeform.com", Version: "v1alpha1", Kind: "KeyRings"}

// Get takes name of the keyRings, and returns the corresponding keyRings object, and an error if there is any.
func (c *FakeKeyRingses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KeyRings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(keyringsesResource, c.ns, name), &v1alpha1.KeyRings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeyRings), err
}

// List takes label and field selectors, and returns the list of KeyRingses that match those selectors.
func (c *FakeKeyRingses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KeyRingsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(keyringsesResource, keyringsesKind, c.ns, opts), &v1alpha1.KeyRingsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KeyRingsList{ListMeta: obj.(*v1alpha1.KeyRingsList).ListMeta}
	for _, item := range obj.(*v1alpha1.KeyRingsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested keyRingses.
func (c *FakeKeyRingses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(keyringsesResource, c.ns, opts))

}

// Create takes the representation of a keyRings and creates it.  Returns the server's representation of the keyRings, and an error, if there is any.
func (c *FakeKeyRingses) Create(ctx context.Context, keyRings *v1alpha1.KeyRings, opts v1.CreateOptions) (result *v1alpha1.KeyRings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(keyringsesResource, c.ns, keyRings), &v1alpha1.KeyRings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeyRings), err
}

// Update takes the representation of a keyRings and updates it. Returns the server's representation of the keyRings, and an error, if there is any.
func (c *FakeKeyRingses) Update(ctx context.Context, keyRings *v1alpha1.KeyRings, opts v1.UpdateOptions) (result *v1alpha1.KeyRings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(keyringsesResource, c.ns, keyRings), &v1alpha1.KeyRings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeyRings), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKeyRingses) UpdateStatus(ctx context.Context, keyRings *v1alpha1.KeyRings, opts v1.UpdateOptions) (*v1alpha1.KeyRings, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(keyringsesResource, "status", c.ns, keyRings), &v1alpha1.KeyRings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeyRings), err
}

// Delete takes name of the keyRings and deletes it. Returns an error if one occurs.
func (c *FakeKeyRingses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(keyringsesResource, c.ns, name), &v1alpha1.KeyRings{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKeyRingses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(keyringsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KeyRingsList{})
	return err
}

// Patch applies the patch and returns the patched keyRings.
func (c *FakeKeyRingses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KeyRings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(keyringsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KeyRings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KeyRings), err
}
