/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/pn/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApplicationChromes implements ApplicationChromeInterface
type FakeApplicationChromes struct {
	Fake *FakePnV1alpha1
	ns   string
}

var applicationchromesResource = schema.GroupVersionResource{Group: "pn.ibm.kubeform.com", Version: "v1alpha1", Resource: "applicationchromes"}

var applicationchromesKind = schema.GroupVersionKind{Group: "pn.ibm.kubeform.com", Version: "v1alpha1", Kind: "ApplicationChrome"}

// Get takes name of the applicationChrome, and returns the corresponding applicationChrome object, and an error if there is any.
func (c *FakeApplicationChromes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ApplicationChrome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(applicationchromesResource, c.ns, name), &v1alpha1.ApplicationChrome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationChrome), err
}

// List takes label and field selectors, and returns the list of ApplicationChromes that match those selectors.
func (c *FakeApplicationChromes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApplicationChromeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(applicationchromesResource, applicationchromesKind, c.ns, opts), &v1alpha1.ApplicationChromeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApplicationChromeList{ListMeta: obj.(*v1alpha1.ApplicationChromeList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApplicationChromeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested applicationChromes.
func (c *FakeApplicationChromes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(applicationchromesResource, c.ns, opts))

}

// Create takes the representation of a applicationChrome and creates it.  Returns the server's representation of the applicationChrome, and an error, if there is any.
func (c *FakeApplicationChromes) Create(ctx context.Context, applicationChrome *v1alpha1.ApplicationChrome, opts v1.CreateOptions) (result *v1alpha1.ApplicationChrome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(applicationchromesResource, c.ns, applicationChrome), &v1alpha1.ApplicationChrome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationChrome), err
}

// Update takes the representation of a applicationChrome and updates it. Returns the server's representation of the applicationChrome, and an error, if there is any.
func (c *FakeApplicationChromes) Update(ctx context.Context, applicationChrome *v1alpha1.ApplicationChrome, opts v1.UpdateOptions) (result *v1alpha1.ApplicationChrome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(applicationchromesResource, c.ns, applicationChrome), &v1alpha1.ApplicationChrome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationChrome), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApplicationChromes) UpdateStatus(ctx context.Context, applicationChrome *v1alpha1.ApplicationChrome, opts v1.UpdateOptions) (*v1alpha1.ApplicationChrome, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(applicationchromesResource, "status", c.ns, applicationChrome), &v1alpha1.ApplicationChrome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationChrome), err
}

// Delete takes name of the applicationChrome and deletes it. Returns an error if one occurs.
func (c *FakeApplicationChromes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(applicationchromesResource, c.ns, name), &v1alpha1.ApplicationChrome{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApplicationChromes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(applicationchromesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApplicationChromeList{})
	return err
}

// Patch applies the patch and returns the patched applicationChrome.
func (c *FakeApplicationChromes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationChrome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(applicationchromesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ApplicationChrome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApplicationChrome), err
}
