/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CaptureListerExpansion allows custom methods to be added to
// CaptureLister.
type CaptureListerExpansion interface{}

// CaptureNamespaceListerExpansion allows custom methods to be added to
// CaptureNamespaceLister.
type CaptureNamespaceListerExpansion interface{}

// ImageListerExpansion allows custom methods to be added to
// ImageLister.
type ImageListerExpansion interface{}

// ImageNamespaceListerExpansion allows custom methods to be added to
// ImageNamespaceLister.
type ImageNamespaceListerExpansion interface{}

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}

// KeyListerExpansion allows custom methods to be added to
// KeyLister.
type KeyListerExpansion interface{}

// KeyNamespaceListerExpansion allows custom methods to be added to
// KeyNamespaceLister.
type KeyNamespaceListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// NetworkPortListerExpansion allows custom methods to be added to
// NetworkPortLister.
type NetworkPortListerExpansion interface{}

// NetworkPortNamespaceListerExpansion allows custom methods to be added to
// NetworkPortNamespaceLister.
type NetworkPortNamespaceListerExpansion interface{}

// NetworkPortAttachListerExpansion allows custom methods to be added to
// NetworkPortAttachLister.
type NetworkPortAttachListerExpansion interface{}

// NetworkPortAttachNamespaceListerExpansion allows custom methods to be added to
// NetworkPortAttachNamespaceLister.
type NetworkPortAttachNamespaceListerExpansion interface{}

// OperationsListerExpansion allows custom methods to be added to
// OperationsLister.
type OperationsListerExpansion interface{}

// OperationsNamespaceListerExpansion allows custom methods to be added to
// OperationsNamespaceLister.
type OperationsNamespaceListerExpansion interface{}

// SnapshotListerExpansion allows custom methods to be added to
// SnapshotLister.
type SnapshotListerExpansion interface{}

// SnapshotNamespaceListerExpansion allows custom methods to be added to
// SnapshotNamespaceLister.
type SnapshotNamespaceListerExpansion interface{}

// VolumeListerExpansion allows custom methods to be added to
// VolumeLister.
type VolumeListerExpansion interface{}

// VolumeNamespaceListerExpansion allows custom methods to be added to
// VolumeNamespaceLister.
type VolumeNamespaceListerExpansion interface{}

// VolumeAttachListerExpansion allows custom methods to be added to
// VolumeAttachLister.
type VolumeAttachListerExpansion interface{}

// VolumeAttachNamespaceListerExpansion allows custom methods to be added to
// VolumeAttachNamespaceLister.
type VolumeAttachNamespaceListerExpansion interface{}
