/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/pi/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeAttaches implements VolumeAttachInterface
type FakeVolumeAttaches struct {
	Fake *FakePiV1alpha1
	ns   string
}

var volumeattachesResource = schema.GroupVersionResource{Group: "pi.ibm.kubeform.com", Version: "v1alpha1", Resource: "volumeattaches"}

var volumeattachesKind = schema.GroupVersionKind{Group: "pi.ibm.kubeform.com", Version: "v1alpha1", Kind: "VolumeAttach"}

// Get takes name of the volumeAttach, and returns the corresponding volumeAttach object, and an error if there is any.
func (c *FakeVolumeAttaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VolumeAttach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volumeattachesResource, c.ns, name), &v1alpha1.VolumeAttach{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeAttach), err
}

// List takes label and field selectors, and returns the list of VolumeAttaches that match those selectors.
func (c *FakeVolumeAttaches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VolumeAttachList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volumeattachesResource, volumeattachesKind, c.ns, opts), &v1alpha1.VolumeAttachList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VolumeAttachList{ListMeta: obj.(*v1alpha1.VolumeAttachList).ListMeta}
	for _, item := range obj.(*v1alpha1.VolumeAttachList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeAttaches.
func (c *FakeVolumeAttaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volumeattachesResource, c.ns, opts))

}

// Create takes the representation of a volumeAttach and creates it.  Returns the server's representation of the volumeAttach, and an error, if there is any.
func (c *FakeVolumeAttaches) Create(ctx context.Context, volumeAttach *v1alpha1.VolumeAttach, opts v1.CreateOptions) (result *v1alpha1.VolumeAttach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volumeattachesResource, c.ns, volumeAttach), &v1alpha1.VolumeAttach{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeAttach), err
}

// Update takes the representation of a volumeAttach and updates it. Returns the server's representation of the volumeAttach, and an error, if there is any.
func (c *FakeVolumeAttaches) Update(ctx context.Context, volumeAttach *v1alpha1.VolumeAttach, opts v1.UpdateOptions) (result *v1alpha1.VolumeAttach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volumeattachesResource, c.ns, volumeAttach), &v1alpha1.VolumeAttach{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeAttach), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeAttaches) UpdateStatus(ctx context.Context, volumeAttach *v1alpha1.VolumeAttach, opts v1.UpdateOptions) (*v1alpha1.VolumeAttach, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(volumeattachesResource, "status", c.ns, volumeAttach), &v1alpha1.VolumeAttach{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeAttach), err
}

// Delete takes name of the volumeAttach and deletes it. Returns an error if one occurs.
func (c *FakeVolumeAttaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(volumeattachesResource, c.ns, name), &v1alpha1.VolumeAttach{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeAttaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volumeattachesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VolumeAttachList{})
	return err
}

// Patch applies the patch and returns the patched volumeAttach.
func (c *FakeVolumeAttaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeAttach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volumeattachesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VolumeAttach{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeAttach), err
}
