/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/dl/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualConnections implements VirtualConnectionInterface
type FakeVirtualConnections struct {
	Fake *FakeDlV1alpha1
	ns   string
}

var virtualconnectionsResource = schema.GroupVersionResource{Group: "dl.ibm.kubeform.com", Version: "v1alpha1", Resource: "virtualconnections"}

var virtualconnectionsKind = schema.GroupVersionKind{Group: "dl.ibm.kubeform.com", Version: "v1alpha1", Kind: "VirtualConnection"}

// Get takes name of the virtualConnection, and returns the corresponding virtualConnection object, and an error if there is any.
func (c *FakeVirtualConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualconnectionsResource, c.ns, name), &v1alpha1.VirtualConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualConnection), err
}

// List takes label and field selectors, and returns the list of VirtualConnections that match those selectors.
func (c *FakeVirtualConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualconnectionsResource, virtualconnectionsKind, c.ns, opts), &v1alpha1.VirtualConnectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualConnectionList{ListMeta: obj.(*v1alpha1.VirtualConnectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualConnections.
func (c *FakeVirtualConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualconnectionsResource, c.ns, opts))

}

// Create takes the representation of a virtualConnection and creates it.  Returns the server's representation of the virtualConnection, and an error, if there is any.
func (c *FakeVirtualConnections) Create(ctx context.Context, virtualConnection *v1alpha1.VirtualConnection, opts v1.CreateOptions) (result *v1alpha1.VirtualConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualconnectionsResource, c.ns, virtualConnection), &v1alpha1.VirtualConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualConnection), err
}

// Update takes the representation of a virtualConnection and updates it. Returns the server's representation of the virtualConnection, and an error, if there is any.
func (c *FakeVirtualConnections) Update(ctx context.Context, virtualConnection *v1alpha1.VirtualConnection, opts v1.UpdateOptions) (result *v1alpha1.VirtualConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualconnectionsResource, c.ns, virtualConnection), &v1alpha1.VirtualConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualConnection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualConnections) UpdateStatus(ctx context.Context, virtualConnection *v1alpha1.VirtualConnection, opts v1.UpdateOptions) (*v1alpha1.VirtualConnection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualconnectionsResource, "status", c.ns, virtualConnection), &v1alpha1.VirtualConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualConnection), err
}

// Delete takes name of the virtualConnection and deletes it. Returns an error if one occurs.
func (c *FakeVirtualConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualconnectionsResource, c.ns, name), &v1alpha1.VirtualConnection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualconnectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualConnectionList{})
	return err
}

// Patch applies the patch and returns the patched virtualConnection.
func (c *FakeVirtualConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualconnectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualConnection), err
}
