/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/apigateway/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEndpointSubscriptions implements EndpointSubscriptionInterface
type FakeEndpointSubscriptions struct {
	Fake *FakeApigatewayV1alpha1
	ns   string
}

var endpointsubscriptionsResource = schema.GroupVersionResource{Group: "apigateway.ibm.kubeform.com", Version: "v1alpha1", Resource: "endpointsubscriptions"}

var endpointsubscriptionsKind = schema.GroupVersionKind{Group: "apigateway.ibm.kubeform.com", Version: "v1alpha1", Kind: "EndpointSubscription"}

// Get takes name of the endpointSubscription, and returns the corresponding endpointSubscription object, and an error if there is any.
func (c *FakeEndpointSubscriptions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EndpointSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(endpointsubscriptionsResource, c.ns, name), &v1alpha1.EndpointSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointSubscription), err
}

// List takes label and field selectors, and returns the list of EndpointSubscriptions that match those selectors.
func (c *FakeEndpointSubscriptions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EndpointSubscriptionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(endpointsubscriptionsResource, endpointsubscriptionsKind, c.ns, opts), &v1alpha1.EndpointSubscriptionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EndpointSubscriptionList{ListMeta: obj.(*v1alpha1.EndpointSubscriptionList).ListMeta}
	for _, item := range obj.(*v1alpha1.EndpointSubscriptionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested endpointSubscriptions.
func (c *FakeEndpointSubscriptions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(endpointsubscriptionsResource, c.ns, opts))

}

// Create takes the representation of a endpointSubscription and creates it.  Returns the server's representation of the endpointSubscription, and an error, if there is any.
func (c *FakeEndpointSubscriptions) Create(ctx context.Context, endpointSubscription *v1alpha1.EndpointSubscription, opts v1.CreateOptions) (result *v1alpha1.EndpointSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(endpointsubscriptionsResource, c.ns, endpointSubscription), &v1alpha1.EndpointSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointSubscription), err
}

// Update takes the representation of a endpointSubscription and updates it. Returns the server's representation of the endpointSubscription, and an error, if there is any.
func (c *FakeEndpointSubscriptions) Update(ctx context.Context, endpointSubscription *v1alpha1.EndpointSubscription, opts v1.UpdateOptions) (result *v1alpha1.EndpointSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(endpointsubscriptionsResource, c.ns, endpointSubscription), &v1alpha1.EndpointSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointSubscription), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEndpointSubscriptions) UpdateStatus(ctx context.Context, endpointSubscription *v1alpha1.EndpointSubscription, opts v1.UpdateOptions) (*v1alpha1.EndpointSubscription, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(endpointsubscriptionsResource, "status", c.ns, endpointSubscription), &v1alpha1.EndpointSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointSubscription), err
}

// Delete takes name of the endpointSubscription and deletes it. Returns an error if one occurs.
func (c *FakeEndpointSubscriptions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(endpointsubscriptionsResource, c.ns, name), &v1alpha1.EndpointSubscription{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEndpointSubscriptions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(endpointsubscriptionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EndpointSubscriptionList{})
	return err
}

// Patch applies the patch and returns the patched endpointSubscription.
func (c *FakeEndpointSubscriptions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EndpointSubscription, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(endpointsubscriptionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EndpointSubscription{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointSubscription), err
}
