apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: configfeatures.app.ibm.kubeform.com
spec:
  group: app.ibm.kubeform.com
  names:
    kind: ConfigFeature
    listKind: ConfigFeatureList
    plural: configfeatures
    singular: configfeature
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  collections:
                    description: List of collection id representing the collections
                      that are associated with the specified feature flag.
                    items:
                      properties:
                        collectionID:
                          description: Collection id.
                          type: string
                      required:
                      - collectionID
                      type: object
                    type: array
                  createdTime:
                    description: Creation time of the feature flag.
                    type: string
                  description:
                    description: Feature description.
                    type: string
                  disabledValue:
                    description: Value of the feature when it is disabled. The value
                      can be BOOLEAN, STRING or a NUMERIC value as per the `type`
                      attribute.
                    type: string
                  enabled:
                    description: The state of the feature flag.
                    type: boolean
                  enabledValue:
                    description: Value of the feature when it is enabled. The value
                      can be BOOLEAN, STRING or a NUMERIC value as per the `type`
                      attribute.
                    type: string
                  environmentID:
                    description: Environment Id.
                    type: string
                  featureID:
                    description: Feature id.
                    type: string
                  guid:
                    description: GUID of the App Configuration service. Get it from
                      the service instance credentials section of the dashboard.
                    type: string
                  href:
                    description: Feature flag URL.
                    type: string
                  id:
                    type: string
                  name:
                    description: Feature name.
                    type: string
                  segmentExists:
                    description: Denotes if the targeting rules are specified for
                      the feature flag.
                    type: boolean
                  segmentRules:
                    description: Specify the targeting rules that is used to set different
                      feature flag values for different segments.
                    items:
                      properties:
                        order:
                          description: Order of the rule, used during evaluation.
                            The evaluation is performed in the order defined and the
                            value associated with the first matching rule is used
                            for evaluation.
                          format: int64
                          type: integer
                        rules:
                          description: Rules array.
                          items:
                            properties:
                              segments:
                                description: List of segment ids that are used for
                                  targeting using the rule.
                                items:
                                  type: string
                                type: array
                            required:
                            - segments
                            type: object
                          type: array
                        value:
                          description: Value to be used for evaluation for this rule.
                            The value can be Boolean, String or a Numeric value as
                            per the `type` attribute.
                          type: string
                      required:
                      - order
                      - rules
                      - value
                      type: object
                    type: array
                  tags:
                    description: Tags associated with the feature.
                    type: string
                  type:
                    description: Type of the feature (BOOLEAN, STRING, NUMERIC).
                    type: string
                  updatedTime:
                    description: Last modified time of the feature flag data.
                    type: string
                required:
                - disabledValue
                - enabledValue
                - environmentID
                - featureID
                - guid
                - name
                - type
                type: object
              state:
                properties:
                  collections:
                    description: List of collection id representing the collections
                      that are associated with the specified feature flag.
                    items:
                      properties:
                        collectionID:
                          description: Collection id.
                          type: string
                      required:
                      - collectionID
                      type: object
                    type: array
                  createdTime:
                    description: Creation time of the feature flag.
                    type: string
                  description:
                    description: Feature description.
                    type: string
                  disabledValue:
                    description: Value of the feature when it is disabled. The value
                      can be BOOLEAN, STRING or a NUMERIC value as per the `type`
                      attribute.
                    type: string
                  enabled:
                    description: The state of the feature flag.
                    type: boolean
                  enabledValue:
                    description: Value of the feature when it is enabled. The value
                      can be BOOLEAN, STRING or a NUMERIC value as per the `type`
                      attribute.
                    type: string
                  environmentID:
                    description: Environment Id.
                    type: string
                  featureID:
                    description: Feature id.
                    type: string
                  guid:
                    description: GUID of the App Configuration service. Get it from
                      the service instance credentials section of the dashboard.
                    type: string
                  href:
                    description: Feature flag URL.
                    type: string
                  id:
                    type: string
                  name:
                    description: Feature name.
                    type: string
                  segmentExists:
                    description: Denotes if the targeting rules are specified for
                      the feature flag.
                    type: boolean
                  segmentRules:
                    description: Specify the targeting rules that is used to set different
                      feature flag values for different segments.
                    items:
                      properties:
                        order:
                          description: Order of the rule, used during evaluation.
                            The evaluation is performed in the order defined and the
                            value associated with the first matching rule is used
                            for evaluation.
                          format: int64
                          type: integer
                        rules:
                          description: Rules array.
                          items:
                            properties:
                              segments:
                                description: List of segment ids that are used for
                                  targeting using the rule.
                                items:
                                  type: string
                                type: array
                            required:
                            - segments
                            type: object
                          type: array
                        value:
                          description: Value to be used for evaluation for this rule.
                            The value can be Boolean, String or a Numeric value as
                            per the `type` attribute.
                          type: string
                      required:
                      - order
                      - rules
                      - value
                      type: object
                    type: array
                  tags:
                    description: Tags associated with the feature.
                    type: string
                  type:
                    description: Type of the feature (BOOLEAN, STRING, NUMERIC).
                    type: string
                  updatedTime:
                    description: Last modified time of the feature flag data.
                    type: string
                required:
                - disabledValue
                - enabledValue
                - environmentID
                - featureID
                - guid
                - name
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
