apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: ratelimits.cis.ibm.kubeform.com
spec:
  group: cis.ibm.kubeform.com
  names:
    kind: RateLimit
    listKind: RateLimitList
    plural: ratelimits
    singular: ratelimit
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  action:
                    description: Rate Limiting Action
                    properties:
                      mode:
                        description: 'Type of action performed.Valid values are: ''simulate'',
                          ''ban'', ''challenge'', ''js_challenge''.'
                        type: string
                      response:
                        description: Rate Limiting Action Response
                        properties:
                          body:
                            description: The body to return. The content here must
                              confirm to the 'content_type'
                            type: string
                          contentType:
                            description: Custom content-type and body to return. It
                              must be one of following 'text/plain', 'text/xml', 'application/json'.
                            type: string
                        required:
                        - body
                        - contentType
                        type: object
                      timeout:
                        description: The time to perform the mitigation action. Timeout
                          be the same or greater than the period.
                        format: int64
                        type: integer
                    required:
                    - mode
                    type: object
                  bypass:
                    description: Bypass URL
                    items:
                      properties:
                        name:
                          description: bypass URL name
                          type: string
                        value:
                          description: bypass URL value
                          type: string
                      type: object
                    type: array
                  cisID:
                    description: CIS Intance CRN
                    type: string
                  correlate:
                    description: Ratelimiting Correlate
                    properties:
                      by:
                        description: Whether to enable NAT based rate limiting
                        type: string
                    type: object
                  description:
                    description: A note that you can use to describe the reason for
                      a rate limiting rule.
                    type: string
                  disabled:
                    description: Whether this rate limiting rule is currently disabled.
                    type: boolean
                  domainID:
                    description: CIS Domain ID
                    type: string
                  id:
                    type: string
                  match:
                    description: Rate Limiting Match
                    properties:
                      request:
                        description: Rate Limiting Match Request
                        properties:
                          methods:
                            description: HTTP Methos of matching request. It can be
                              one or many. Example methods 'POST', 'PUT'
                            items:
                              type: string
                            type: array
                          schemes:
                            description: HTTP Schemes of matching request. It can
                              be one or many. Example schemes 'HTTP', 'HTTPS'.
                            items:
                              type: string
                            type: array
                          url:
                            description: URL pattern of matching request
                            type: string
                        type: object
                      response:
                        description: Rate Limiting Response
                        properties:
                          headers:
                            items:
                              properties:
                                name:
                                  description: The name of the response header to
                                    match.
                                  type: string
                                op:
                                  description: The operator when matching. Valid values
                                    are 'eq' and 'ne'.
                                  type: string
                                value:
                                  description: The value of the header, which is exactly
                                    matched.
                                  type: string
                              type: object
                            type: array
                          originTraffic:
                            description: Origin Traffic of matching response.
                            type: boolean
                          status:
                            description: HTTP Status Codes of matching response. It
                              can be one or many. Example status codes '403', '401
                            items:
                              format: int64
                              type: integer
                            type: array
                        type: object
                    type: object
                  period:
                    description: Rate Limiting Period
                    format: int64
                    type: integer
                  ruleID:
                    description: Rate Limit rule Id
                    type: string
                  threshold:
                    description: Rate Limiting Threshold
                    format: int64
                    type: integer
                required:
                - action
                - cisID
                - domainID
                - period
                - threshold
                type: object
              state:
                properties:
                  action:
                    description: Rate Limiting Action
                    properties:
                      mode:
                        description: 'Type of action performed.Valid values are: ''simulate'',
                          ''ban'', ''challenge'', ''js_challenge''.'
                        type: string
                      response:
                        description: Rate Limiting Action Response
                        properties:
                          body:
                            description: The body to return. The content here must
                              confirm to the 'content_type'
                            type: string
                          contentType:
                            description: Custom content-type and body to return. It
                              must be one of following 'text/plain', 'text/xml', 'application/json'.
                            type: string
                        required:
                        - body
                        - contentType
                        type: object
                      timeout:
                        description: The time to perform the mitigation action. Timeout
                          be the same or greater than the period.
                        format: int64
                        type: integer
                    required:
                    - mode
                    type: object
                  bypass:
                    description: Bypass URL
                    items:
                      properties:
                        name:
                          description: bypass URL name
                          type: string
                        value:
                          description: bypass URL value
                          type: string
                      type: object
                    type: array
                  cisID:
                    description: CIS Intance CRN
                    type: string
                  correlate:
                    description: Ratelimiting Correlate
                    properties:
                      by:
                        description: Whether to enable NAT based rate limiting
                        type: string
                    type: object
                  description:
                    description: A note that you can use to describe the reason for
                      a rate limiting rule.
                    type: string
                  disabled:
                    description: Whether this rate limiting rule is currently disabled.
                    type: boolean
                  domainID:
                    description: CIS Domain ID
                    type: string
                  id:
                    type: string
                  match:
                    description: Rate Limiting Match
                    properties:
                      request:
                        description: Rate Limiting Match Request
                        properties:
                          methods:
                            description: HTTP Methos of matching request. It can be
                              one or many. Example methods 'POST', 'PUT'
                            items:
                              type: string
                            type: array
                          schemes:
                            description: HTTP Schemes of matching request. It can
                              be one or many. Example schemes 'HTTP', 'HTTPS'.
                            items:
                              type: string
                            type: array
                          url:
                            description: URL pattern of matching request
                            type: string
                        type: object
                      response:
                        description: Rate Limiting Response
                        properties:
                          headers:
                            items:
                              properties:
                                name:
                                  description: The name of the response header to
                                    match.
                                  type: string
                                op:
                                  description: The operator when matching. Valid values
                                    are 'eq' and 'ne'.
                                  type: string
                                value:
                                  description: The value of the header, which is exactly
                                    matched.
                                  type: string
                              type: object
                            type: array
                          originTraffic:
                            description: Origin Traffic of matching response.
                            type: boolean
                          status:
                            description: HTTP Status Codes of matching response. It
                              can be one or many. Example status codes '403', '401
                            items:
                              format: int64
                              type: integer
                            type: array
                        type: object
                    type: object
                  period:
                    description: Rate Limiting Period
                    format: int64
                    type: integer
                  ruleID:
                    description: Rate Limit rule Id
                    type: string
                  threshold:
                    description: Rate Limiting Threshold
                    format: int64
                    type: integer
                required:
                - action
                - cisID
                - domainID
                - period
                - threshold
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
