apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: rangeapps.cis.ibm.kubeform.com
spec:
  group: cis.ibm.kubeform.com
  names:
    kind: RangeApp
    listKind: RangeAppList
    plural: rangeapps
    singular: rangeapp
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  appID:
                    description: Application identifier
                    type: string
                  cisID:
                    description: CIS Intance CRN
                    type: string
                  createdOn:
                    description: created on date
                    type: string
                  dns:
                    description: Name of the DNS record for this application
                    type: string
                  dnsType:
                    description: Type of the DNS record for this application
                    type: string
                  domainID:
                    description: CIS Domain ID
                    type: string
                  edgeIPSConnectivity:
                    description: Specifies the IP version.
                    type: string
                  edgeIPSType:
                    description: The type of edge IP configuration.
                    type: string
                  id:
                    type: string
                  ipFirewall:
                    description: Enables the IP Firewall for this application. Only
                      available for TCP applications.
                    type: boolean
                  modifiedOn:
                    description: modified on date
                    type: string
                  originDNS:
                    description: DNS record pointing to the origin for this Range
                      application.
                    type: string
                  originDirect:
                    description: IP address and port of the origin for this Range
                      application.
                    items:
                      type: string
                    type: array
                  originPort:
                    description: Port at the origin that listens to traffic
                    format: int64
                    type: integer
                  protocol:
                    description: Defines the protocol and port for this application
                    type: string
                  proxyProtocol:
                    description: Allows for the true client IP to be passed to the
                      service.
                    type: string
                  tls:
                    description: Configure if and how TLS connections are terminated
                      at the edge.
                    type: string
                  trafficType:
                    description: Configure how traffic is handled at the edge.
                    type: string
                required:
                - cisID
                - dns
                - dnsType
                - domainID
                - protocol
                type: object
              state:
                properties:
                  appID:
                    description: Application identifier
                    type: string
                  cisID:
                    description: CIS Intance CRN
                    type: string
                  createdOn:
                    description: created on date
                    type: string
                  dns:
                    description: Name of the DNS record for this application
                    type: string
                  dnsType:
                    description: Type of the DNS record for this application
                    type: string
                  domainID:
                    description: CIS Domain ID
                    type: string
                  edgeIPSConnectivity:
                    description: Specifies the IP version.
                    type: string
                  edgeIPSType:
                    description: The type of edge IP configuration.
                    type: string
                  id:
                    type: string
                  ipFirewall:
                    description: Enables the IP Firewall for this application. Only
                      available for TCP applications.
                    type: boolean
                  modifiedOn:
                    description: modified on date
                    type: string
                  originDNS:
                    description: DNS record pointing to the origin for this Range
                      application.
                    type: string
                  originDirect:
                    description: IP address and port of the origin for this Range
                      application.
                    items:
                      type: string
                    type: array
                  originPort:
                    description: Port at the origin that listens to traffic
                    format: int64
                    type: integer
                  protocol:
                    description: Defines the protocol and port for this application
                    type: string
                  proxyProtocol:
                    description: Allows for the true client IP to be passed to the
                      service.
                    type: string
                  tls:
                    description: Configure if and how TLS connections are terminated
                      at the edge.
                    type: string
                  trafficType:
                    description: Configure how traffic is handled at the edge.
                    type: string
                required:
                - cisID
                - dns
                - dnsType
                - domainID
                - protocol
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
