apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: offerings.cm.ibm.kubeform.com
spec:
  group: cm.ibm.kubeform.com
  names:
    kind: Offering
    listKind: OfferingList
    plural: offerings
    singular: offering
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  catalogID:
                    description: The id of the catalog containing this offering.
                    type: string
                  catalogName:
                    description: The name of the catalog.
                    type: string
                  crn:
                    description: The crn for this specific offering.
                    type: string
                  disclaimer:
                    description: A disclaimer for this offering.
                    type: string
                  hidden:
                    description: Determine if this offering should be displayed in
                      the Consumption UI.
                    type: boolean
                  ibmPublishApproved:
                    description: Indicates if this offering has been approved for
                      use by all IBMers.
                    type: boolean
                  id:
                    type: string
                  label:
                    description: Display Name in the requested language.
                    type: string
                  longDescription:
                    description: Long description in the requested language.
                    type: string
                  name:
                    description: The programmatic name of this offering.
                    type: string
                  offeringDocsURL:
                    description: URL for an additional docs with this offering.
                    type: string
                  offeringID:
                    description: The id of the catalog containing this offering.
                    type: string
                  offeringIconURL:
                    description: URL for an icon associated with this offering.
                    type: string
                  offeringSupportURL:
                    description: URL to be displayed in the Consumption UI for getting
                      support on this offering.
                    type: string
                  permitRequestIbmPublicPublish:
                    description: Is it permitted to request publishing to IBM or Public.
                    type: boolean
                  portalApprovalRecord:
                    description: The portal's approval record ID.
                    type: string
                  portalUiURL:
                    description: The portal UI URL.
                    type: string
                  publicOriginalCrn:
                    description: The original offering CRN that this publish entry
                      came from.
                    type: string
                  publicPublishApproved:
                    description: Indicates if this offering has been approved for
                      use by all IBM Cloud users.
                    type: boolean
                  publishPublicCrn:
                    description: The crn of the public catalog entry of this offering.
                    type: string
                  repoInfo:
                    description: Repository info for offerings.
                    items:
                      properties:
                        token:
                          description: Token for private repos.
                          type: string
                        type:
                          description: Public or enterprise GitHub.
                          type: string
                      type: object
                    type: array
                  shortDescription:
                    description: Short description in the requested language.
                    type: string
                  tags:
                    description: List of tags associated with this catalog.
                    items:
                      type: string
                    type: array
                  url:
                    description: The url for this specific offering.
                    type: string
                required:
                - catalogID
                - label
                type: object
              state:
                properties:
                  catalogID:
                    description: The id of the catalog containing this offering.
                    type: string
                  catalogName:
                    description: The name of the catalog.
                    type: string
                  crn:
                    description: The crn for this specific offering.
                    type: string
                  disclaimer:
                    description: A disclaimer for this offering.
                    type: string
                  hidden:
                    description: Determine if this offering should be displayed in
                      the Consumption UI.
                    type: boolean
                  ibmPublishApproved:
                    description: Indicates if this offering has been approved for
                      use by all IBMers.
                    type: boolean
                  id:
                    type: string
                  label:
                    description: Display Name in the requested language.
                    type: string
                  longDescription:
                    description: Long description in the requested language.
                    type: string
                  name:
                    description: The programmatic name of this offering.
                    type: string
                  offeringDocsURL:
                    description: URL for an additional docs with this offering.
                    type: string
                  offeringID:
                    description: The id of the catalog containing this offering.
                    type: string
                  offeringIconURL:
                    description: URL for an icon associated with this offering.
                    type: string
                  offeringSupportURL:
                    description: URL to be displayed in the Consumption UI for getting
                      support on this offering.
                    type: string
                  permitRequestIbmPublicPublish:
                    description: Is it permitted to request publishing to IBM or Public.
                    type: boolean
                  portalApprovalRecord:
                    description: The portal's approval record ID.
                    type: string
                  portalUiURL:
                    description: The portal UI URL.
                    type: string
                  publicOriginalCrn:
                    description: The original offering CRN that this publish entry
                      came from.
                    type: string
                  publicPublishApproved:
                    description: Indicates if this offering has been approved for
                      use by all IBM Cloud users.
                    type: boolean
                  publishPublicCrn:
                    description: The crn of the public catalog entry of this offering.
                    type: string
                  repoInfo:
                    description: Repository info for offerings.
                    items:
                      properties:
                        token:
                          description: Token for private repos.
                          type: string
                        type:
                          description: Public or enterprise GitHub.
                          type: string
                      type: object
                    type: array
                  shortDescription:
                    description: Short description in the requested language.
                    type: string
                  tags:
                    description: List of tags associated with this catalog.
                    items:
                      type: string
                    type: array
                  url:
                    description: The url for this specific offering.
                    type: string
                required:
                - catalogID
                - label
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
