apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: baremetals.compute.ibm.kubeform.com
spec:
  group: compute.ibm.kubeform.com
  names:
    kind: BareMetal
    listKind: BareMetalList
    plural: baremetals
    singular: baremetal
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  blockStorageIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  datacenter:
                    type: string
                  diskKeyNames:
                    items:
                      type: string
                    type: array
                  domain:
                    description: Domain name
                    type: string
                  extendedHardwareTesting:
                    type: boolean
                  fileStorageIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  fixedConfigPreset:
                    description: Fixed config preset value
                    type: string
                  globalIdentifier:
                    description: The unique global identifier of the bare metal server
                    type: string
                  gpuKeyName:
                    type: string
                  gpuSecondaryKeyName:
                    type: string
                  hostname:
                    description: Host name
                    type: string
                  hourlyBilling:
                    description: Enables hourly billing
                    type: boolean
                  id:
                    type: string
                  imageTemplateID:
                    description: OS image template ID
                    format: int64
                    type: integer
                  ipv6Address:
                    type: string
                  ipv6AddressID:
                    format: int64
                    type: integer
                  ipv6Enabled:
                    description: Boolean value true if IPV6 ia enabled or false
                    type: boolean
                  ipv6StaticEnabled:
                    description: boolean value true if ipv6 static is enabled else
                      false
                    type: boolean
                  memory:
                    format: int64
                    type: integer
                  networkSpeed:
                    description: Network speed in MBPS
                    format: int64
                    type: integer
                  notes:
                    description: Optional notes info
                    type: string
                  osKeyName:
                    type: string
                  osReferenceCode:
                    description: OS refernece code value
                    type: string
                  packageKeyName:
                    type: string
                  postInstallScriptURI:
                    type: string
                  privateIpv4Address:
                    type: string
                  privateIpv4AddressID:
                    format: int64
                    type: integer
                  privateNetworkOnly:
                    description: only private network configured if is true
                    type: boolean
                  privateSubnet:
                    type: string
                  privateVLANID:
                    format: int64
                    type: integer
                  processKeyName:
                    type: string
                  publicBandwidth:
                    format: int64
                    type: integer
                  publicIpv4Address:
                    type: string
                  publicIpv4AddressID:
                    format: int64
                    type: integer
                  publicSubnet:
                    type: string
                  publicVLANID:
                    format: int64
                    type: integer
                  quoteID:
                    description: Quote ID for Quote based provisioning
                    format: int64
                    type: integer
                  redundantNetwork:
                    type: boolean
                  redundantPowerSupply:
                    type: boolean
                  restrictedNetwork:
                    type: boolean
                  secondaryIPAddresses:
                    items:
                      type: string
                    type: array
                  secondaryIPCount:
                    description: Secondary IP addresses count
                    format: int64
                    type: integer
                  softwareGuardExtensions:
                    type: boolean
                  sshKeyIDS:
                    description: SSH KEY IDS list
                    items:
                      format: int64
                      type: integer
                    type: array
                  storageGroups:
                    items:
                      properties:
                        arraySize:
                          description: Array size of harddrives list
                          format: int64
                          type: integer
                        arrayTypeID:
                          description: Array type ID
                          format: int64
                          type: integer
                        hardDrives:
                          description: Hard-drives List
                          items:
                            format: int64
                            type: integer
                          type: array
                        partitionTemplateID:
                          description: Partition template ID
                          format: int64
                          type: integer
                      required:
                      - arrayTypeID
                      - hardDrives
                      type: object
                    type: array
                  tags:
                    items:
                      type: string
                    type: array
                  tcpMonitoring:
                    description: TCP monitoring enabled if set as true
                    type: boolean
                  unbondedNetwork:
                    type: boolean
                  userMetadata:
                    description: User metadata info
                    type: string
                required:
                - domain
                type: object
              state:
                properties:
                  blockStorageIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  datacenter:
                    type: string
                  diskKeyNames:
                    items:
                      type: string
                    type: array
                  domain:
                    description: Domain name
                    type: string
                  extendedHardwareTesting:
                    type: boolean
                  fileStorageIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  fixedConfigPreset:
                    description: Fixed config preset value
                    type: string
                  globalIdentifier:
                    description: The unique global identifier of the bare metal server
                    type: string
                  gpuKeyName:
                    type: string
                  gpuSecondaryKeyName:
                    type: string
                  hostname:
                    description: Host name
                    type: string
                  hourlyBilling:
                    description: Enables hourly billing
                    type: boolean
                  id:
                    type: string
                  imageTemplateID:
                    description: OS image template ID
                    format: int64
                    type: integer
                  ipv6Address:
                    type: string
                  ipv6AddressID:
                    format: int64
                    type: integer
                  ipv6Enabled:
                    description: Boolean value true if IPV6 ia enabled or false
                    type: boolean
                  ipv6StaticEnabled:
                    description: boolean value true if ipv6 static is enabled else
                      false
                    type: boolean
                  memory:
                    format: int64
                    type: integer
                  networkSpeed:
                    description: Network speed in MBPS
                    format: int64
                    type: integer
                  notes:
                    description: Optional notes info
                    type: string
                  osKeyName:
                    type: string
                  osReferenceCode:
                    description: OS refernece code value
                    type: string
                  packageKeyName:
                    type: string
                  postInstallScriptURI:
                    type: string
                  privateIpv4Address:
                    type: string
                  privateIpv4AddressID:
                    format: int64
                    type: integer
                  privateNetworkOnly:
                    description: only private network configured if is true
                    type: boolean
                  privateSubnet:
                    type: string
                  privateVLANID:
                    format: int64
                    type: integer
                  processKeyName:
                    type: string
                  publicBandwidth:
                    format: int64
                    type: integer
                  publicIpv4Address:
                    type: string
                  publicIpv4AddressID:
                    format: int64
                    type: integer
                  publicSubnet:
                    type: string
                  publicVLANID:
                    format: int64
                    type: integer
                  quoteID:
                    description: Quote ID for Quote based provisioning
                    format: int64
                    type: integer
                  redundantNetwork:
                    type: boolean
                  redundantPowerSupply:
                    type: boolean
                  restrictedNetwork:
                    type: boolean
                  secondaryIPAddresses:
                    items:
                      type: string
                    type: array
                  secondaryIPCount:
                    description: Secondary IP addresses count
                    format: int64
                    type: integer
                  softwareGuardExtensions:
                    type: boolean
                  sshKeyIDS:
                    description: SSH KEY IDS list
                    items:
                      format: int64
                      type: integer
                    type: array
                  storageGroups:
                    items:
                      properties:
                        arraySize:
                          description: Array size of harddrives list
                          format: int64
                          type: integer
                        arrayTypeID:
                          description: Array type ID
                          format: int64
                          type: integer
                        hardDrives:
                          description: Hard-drives List
                          items:
                            format: int64
                            type: integer
                          type: array
                        partitionTemplateID:
                          description: Partition template ID
                          format: int64
                          type: integer
                      required:
                      - arrayTypeID
                      - hardDrives
                      type: object
                    type: array
                  tags:
                    items:
                      type: string
                    type: array
                  tcpMonitoring:
                    description: TCP monitoring enabled if set as true
                    type: boolean
                  unbondedNetwork:
                    type: boolean
                  userMetadata:
                    description: User metadata info
                    type: string
                required:
                - domain
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
