apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: records.dns.ibm.kubeform.com
spec:
  group: dns.ibm.kubeform.com
  names:
    kind: Record
    listKind: RecordList
    plural: records
    singular: record
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  data:
                    description: DNS record data
                    type: string
                  domainID:
                    description: Domain ID of dns record instance
                    format: int64
                    type: integer
                  expire:
                    description: DNS record expiry info
                    format: int64
                    type: integer
                  host:
                    description: Hostname
                    type: string
                  id:
                    type: string
                  minimumTtl:
                    description: Minimun TTL configuration
                    format: int64
                    type: integer
                  mxPriority:
                    description: Maximum priority
                    format: int64
                    type: integer
                  port:
                    description: port number
                    format: int64
                    type: integer
                  priority:
                    description: priority info
                    format: int64
                    type: integer
                  protocol:
                    description: protocol info
                    type: string
                  refresh:
                    description: refresh rate
                    format: int64
                    type: integer
                  responsiblePerson:
                    description: Responsible person for DNS record
                    type: string
                  retry:
                    description: Retry count
                    format: int64
                    type: integer
                  service:
                    description: service info
                    type: string
                  tags:
                    description: tags set for the resource
                    items:
                      type: string
                    type: array
                  ttl:
                    description: TTL configuration
                    format: int64
                    type: integer
                  type:
                    description: DNS record type
                    type: string
                  weight:
                    description: weight info
                    format: int64
                    type: integer
                required:
                - data
                - domainID
                - host
                - ttl
                - type
                type: object
              state:
                properties:
                  data:
                    description: DNS record data
                    type: string
                  domainID:
                    description: Domain ID of dns record instance
                    format: int64
                    type: integer
                  expire:
                    description: DNS record expiry info
                    format: int64
                    type: integer
                  host:
                    description: Hostname
                    type: string
                  id:
                    type: string
                  minimumTtl:
                    description: Minimun TTL configuration
                    format: int64
                    type: integer
                  mxPriority:
                    description: Maximum priority
                    format: int64
                    type: integer
                  port:
                    description: port number
                    format: int64
                    type: integer
                  priority:
                    description: priority info
                    format: int64
                    type: integer
                  protocol:
                    description: protocol info
                    type: string
                  refresh:
                    description: refresh rate
                    format: int64
                    type: integer
                  responsiblePerson:
                    description: Responsible person for DNS record
                    type: string
                  retry:
                    description: Retry count
                    format: int64
                    type: integer
                  service:
                    description: service info
                    type: string
                  tags:
                    description: tags set for the resource
                    items:
                      type: string
                    type: array
                  ttl:
                    description: TTL configuration
                    format: int64
                    type: integer
                  type:
                    description: DNS record type
                    type: string
                  weight:
                    description: weight info
                    format: int64
                    type: integer
                required:
                - data
                - domainID
                - host
                - ttl
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
