apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: accounts.enterprise.ibm.kubeform.com
spec:
  group: enterprise.ibm.kubeform.com
  names:
    kind: Account
    listKind: AccountList
    plural: accounts
    singular: account
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accountID:
                    description: The source account id of account to be imported
                    type: string
                  createdAt:
                    description: The time stamp at which the account was created.
                    type: string
                  createdBy:
                    description: The IAM ID of the user or service that created the
                      account.
                    type: string
                  crn:
                    description: The Cloud Resource Name (CRN) of the account.
                    type: string
                  enterpriseAccountID:
                    description: The enterprise account ID.
                    type: string
                  enterpriseID:
                    description: The enterprise ID that the account is a part of.
                    type: string
                  enterprisePath:
                    description: The path from the enterprise to this particular account.
                    type: string
                  id:
                    type: string
                  isEnterpriseAccount:
                    description: The flag to indicate whether the account is an enterprise
                      account or not.
                    type: boolean
                  name:
                    description: The name of the account. This field must have 3 -
                      60 characters.
                    type: string
                  ownerEmail:
                    description: The email address of the owner of the account.
                    type: string
                  ownerIamID:
                    description: The IAM ID of the account owner, such as `IBMid-0123ABC`.
                      The IAM ID must already exist.
                    type: string
                  paid:
                    description: The type of account - whether it is free or paid.
                    type: boolean
                  parent:
                    description: The CRN of the parent under which the account will
                      be created. The parent can be an existing account group or the
                      enterprise itself.
                    type: string
                  state:
                    description: The state of the account.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The time stamp at which the account was last updated.
                    type: string
                  updatedBy:
                    description: The IAM ID of the user or service that updated the
                      account.
                    type: string
                  url:
                    description: The URL of the account.
                    type: string
                required:
                - parent
                type: object
              state:
                properties:
                  accountID:
                    description: The source account id of account to be imported
                    type: string
                  createdAt:
                    description: The time stamp at which the account was created.
                    type: string
                  createdBy:
                    description: The IAM ID of the user or service that created the
                      account.
                    type: string
                  crn:
                    description: The Cloud Resource Name (CRN) of the account.
                    type: string
                  enterpriseAccountID:
                    description: The enterprise account ID.
                    type: string
                  enterpriseID:
                    description: The enterprise ID that the account is a part of.
                    type: string
                  enterprisePath:
                    description: The path from the enterprise to this particular account.
                    type: string
                  id:
                    type: string
                  isEnterpriseAccount:
                    description: The flag to indicate whether the account is an enterprise
                      account or not.
                    type: boolean
                  name:
                    description: The name of the account. This field must have 3 -
                      60 characters.
                    type: string
                  ownerEmail:
                    description: The email address of the owner of the account.
                    type: string
                  ownerIamID:
                    description: The IAM ID of the account owner, such as `IBMid-0123ABC`.
                      The IAM ID must already exist.
                    type: string
                  paid:
                    description: The type of account - whether it is free or paid.
                    type: boolean
                  parent:
                    description: The CRN of the parent under which the account will
                      be created. The parent can be an existing account group or the
                      enterprise itself.
                    type: string
                  state:
                    description: The state of the account.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The time stamp at which the account was last updated.
                    type: string
                  updatedBy:
                    description: The IAM ID of the user or service that updated the
                      account.
                    type: string
                  url:
                    description: The URL of the account.
                    type: string
                required:
                - parent
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
