apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: accountsettings.iam.ibm.kubeform.com
spec:
  group: iam.ibm.kubeform.com
  names:
    kind: AccountSettings
    listKind: AccountSettingsList
    plural: accountsettings
    singular: accountsettings
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  allowedIPAddresses:
                    description: Defines the IP addresses and subnets from which IAM
                      tokens can be created for the account.
                    type: string
                  entityTag:
                    description: Version of the account settings.
                    type: string
                  history:
                    description: History of the Account Settings.
                    items:
                      properties:
                        action:
                          description: Action of the history entry.
                          type: string
                        iamID:
                          description: IAM ID of the identity which triggered the
                            action.
                          type: string
                        iamIDAccount:
                          description: Account of the identity which triggered the
                            action.
                          type: string
                        message:
                          description: Message which summarizes the executed action.
                          type: string
                        params:
                          description: Params of the history entry.
                          items:
                            type: string
                          type: array
                        timestamp:
                          description: Timestamp when the action was triggered.
                          type: string
                      required:
                      - action
                      - iamID
                      - iamIDAccount
                      - message
                      - params
                      - timestamp
                      type: object
                    type: array
                  id:
                    type: string
                  ifMatch:
                    description: Version of the account settings to be updated. Specify
                      the version that you retrieved as entity_tag (ETag header) when
                      reading the account. This value helps identifying parallel usage
                      of this API. Pass * to indicate to update any version available.
                      This might result in stale updates.
                    type: string
                  includeHistory:
                    description: Defines if the entity history is included in the
                      response.
                    type: boolean
                  maxSessionsPerIdentity:
                    description: 'Defines the max allowed sessions per identity required
                      by the account. Value values: * Any whole number greater than
                      ''0''   * NOT_SET - To unset account setting and use service
                      default.'
                    type: string
                  mfa:
                    description: 'Defines the MFA trait for the account. Valid values:  *
                      NONE - No MFA trait set  * TOTP - For all non-federated IBMId
                      users  * TOTP4ALL - For all users  * LEVEL1 - Email-based MFA
                      for all users  * LEVEL2 - TOTP-based MFA for all users  * LEVEL3
                      - U2F MFA for all users.'
                    type: string
                  restrictCreatePlatformApikey:
                    description: 'Defines whether or not creating platform API keys
                      is access controlled. Valid values:  * RESTRICTED - to apply
                      access control  * NOT_RESTRICTED - to remove access control  *
                      NOT_SET - to ''unset'' a previous set value.'
                    type: string
                  restrictCreateServiceID:
                    description: 'Defines whether or not creating a Service Id is
                      access controlled. Valid values:  * RESTRICTED - to apply access
                      control  * NOT_RESTRICTED - to remove access control  * NOT_SET
                      - to ''unset'' a previous set value.'
                    type: string
                  sessionExpirationInSeconds:
                    description: 'Defines the session expiration in seconds for the
                      account. Valid values:  * Any whole number between between ''900''
                      and ''86400''  * NOT_SET - To unset account setting and use
                      service default.'
                    type: string
                  sessionInvalidationInSeconds:
                    description: 'Defines the period of time in seconds in which a
                      session will be invalidated due  to inactivity. Valid values:   *
                      Any whole number between ''900'' and ''7200''   * NOT_SET -
                      To unset account setting and use service default.'
                    type: string
                type: object
              state:
                properties:
                  allowedIPAddresses:
                    description: Defines the IP addresses and subnets from which IAM
                      tokens can be created for the account.
                    type: string
                  entityTag:
                    description: Version of the account settings.
                    type: string
                  history:
                    description: History of the Account Settings.
                    items:
                      properties:
                        action:
                          description: Action of the history entry.
                          type: string
                        iamID:
                          description: IAM ID of the identity which triggered the
                            action.
                          type: string
                        iamIDAccount:
                          description: Account of the identity which triggered the
                            action.
                          type: string
                        message:
                          description: Message which summarizes the executed action.
                          type: string
                        params:
                          description: Params of the history entry.
                          items:
                            type: string
                          type: array
                        timestamp:
                          description: Timestamp when the action was triggered.
                          type: string
                      required:
                      - action
                      - iamID
                      - iamIDAccount
                      - message
                      - params
                      - timestamp
                      type: object
                    type: array
                  id:
                    type: string
                  ifMatch:
                    description: Version of the account settings to be updated. Specify
                      the version that you retrieved as entity_tag (ETag header) when
                      reading the account. This value helps identifying parallel usage
                      of this API. Pass * to indicate to update any version available.
                      This might result in stale updates.
                    type: string
                  includeHistory:
                    description: Defines if the entity history is included in the
                      response.
                    type: boolean
                  maxSessionsPerIdentity:
                    description: 'Defines the max allowed sessions per identity required
                      by the account. Value values: * Any whole number greater than
                      ''0''   * NOT_SET - To unset account setting and use service
                      default.'
                    type: string
                  mfa:
                    description: 'Defines the MFA trait for the account. Valid values:  *
                      NONE - No MFA trait set  * TOTP - For all non-federated IBMId
                      users  * TOTP4ALL - For all users  * LEVEL1 - Email-based MFA
                      for all users  * LEVEL2 - TOTP-based MFA for all users  * LEVEL3
                      - U2F MFA for all users.'
                    type: string
                  restrictCreatePlatformApikey:
                    description: 'Defines whether or not creating platform API keys
                      is access controlled. Valid values:  * RESTRICTED - to apply
                      access control  * NOT_RESTRICTED - to remove access control  *
                      NOT_SET - to ''unset'' a previous set value.'
                    type: string
                  restrictCreateServiceID:
                    description: 'Defines whether or not creating a Service Id is
                      access controlled. Valid values:  * RESTRICTED - to apply access
                      control  * NOT_RESTRICTED - to remove access control  * NOT_SET
                      - to ''unset'' a previous set value.'
                    type: string
                  sessionExpirationInSeconds:
                    description: 'Defines the session expiration in seconds for the
                      account. Valid values:  * Any whole number between between ''900''
                      and ''86400''  * NOT_SET - To unset account setting and use
                      service default.'
                    type: string
                  sessionInvalidationInSeconds:
                    description: 'Defines the period of time in seconds in which a
                      session will be invalidated due  to inactivity. Valid values:   *
                      Any whole number between ''900'' and ''7200''   * NOT_SET -
                      To unset account setting and use service default.'
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
