apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: apikeys.iam.ibm.kubeform.com
spec:
  group: iam.ibm.kubeform.com
  names:
    kind: ApiKey
    listKind: ApiKeyList
    plural: apikeys
    singular: apikey
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accountID:
                    description: The account ID of the API key.
                    type: string
                  apikeyID:
                    description: Unique identifier of this API Key.
                    type: string
                  createdAt:
                    description: If set contains a date time string of the creation
                      date in ISO format.
                    type: string
                  createdBy:
                    description: IAM ID of the user or service which created the API
                      key.
                    type: string
                  crn:
                    description: 'Cloud Resource Name of the item. Example Cloud Resource
                      Name: ''crn:v1:bluemix:public:iam-identity:us-south:a/myaccount::apikey:1234-9012-5678''.'
                    type: string
                  description:
                    description: The optional description of the API key. The 'description'
                      property is only available if a description was provided during
                      a create of an API key.
                    type: string
                  entityLock:
                    description: Indicates if the API key is locked for further write
                      operations. False by default.
                    type: string
                  entityTag:
                    description: Version of the API Key details object. You need to
                      specify this value when updating the API key to avoid stale
                      updates.
                    type: string
                  file:
                    description: File where api key is to be stored
                    type: string
                  iamID:
                    description: The iam_id that this API key authenticates.
                    type: string
                  id:
                    type: string
                  locked:
                    description: The API key cannot be changed if set to true.
                    type: boolean
                  modifiedAt:
                    description: If set contains a date time string of the last modification
                      date in ISO format.
                    type: string
                  name:
                    description: Name of the API key. The name is not checked for
                      uniqueness. Therefore multiple names with the same value can
                      exist. Access is done via the UUID of the API key.
                    type: string
                  storeValue:
                    description: Send true or false to set whether the API key value
                      is retrievable in the future by using the Get details of an
                      API key request. If you create an API key for a user, you must
                      specify `false` or omit the value. We don't allow storing of
                      API keys for users.
                    type: boolean
                required:
                - name
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  accountID:
                    description: The account ID of the API key.
                    type: string
                  apikeyID:
                    description: Unique identifier of this API Key.
                    type: string
                  createdAt:
                    description: If set contains a date time string of the creation
                      date in ISO format.
                    type: string
                  createdBy:
                    description: IAM ID of the user or service which created the API
                      key.
                    type: string
                  crn:
                    description: 'Cloud Resource Name of the item. Example Cloud Resource
                      Name: ''crn:v1:bluemix:public:iam-identity:us-south:a/myaccount::apikey:1234-9012-5678''.'
                    type: string
                  description:
                    description: The optional description of the API key. The 'description'
                      property is only available if a description was provided during
                      a create of an API key.
                    type: string
                  entityLock:
                    description: Indicates if the API key is locked for further write
                      operations. False by default.
                    type: string
                  entityTag:
                    description: Version of the API Key details object. You need to
                      specify this value when updating the API key to avoid stale
                      updates.
                    type: string
                  file:
                    description: File where api key is to be stored
                    type: string
                  iamID:
                    description: The iam_id that this API key authenticates.
                    type: string
                  id:
                    type: string
                  locked:
                    description: The API key cannot be changed if set to true.
                    type: boolean
                  modifiedAt:
                    description: If set contains a date time string of the last modification
                      date in ISO format.
                    type: string
                  name:
                    description: Name of the API key. The name is not checked for
                      uniqueness. Therefore multiple names with the same value can
                      exist. Access is done via the UUID of the API key.
                    type: string
                  storeValue:
                    description: Send true or false to set whether the API key value
                      is retrievable in the future by using the Get details of an
                      API key request. If you create an API key for a user, you must
                      specify `false` or omit the value. We don't allow storing of
                      API keys for users.
                    type: boolean
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
