apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instancegroupmanageractions.is.ibm.kubeform.com
spec:
  group: is.ibm.kubeform.com
  names:
    kind: InstanceGroupManagerAction
    listKind: InstanceGroupManagerActionList
    plural: instancegroupmanageractions
    singular: instancegroupmanageraction
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  actionID:
                    description: Instance group manager action ID
                    type: string
                  actionType:
                    description: The type of action for the instance group.
                    type: string
                  autoDelete:
                    type: boolean
                  autoDeleteTimeout:
                    format: int64
                    type: integer
                  createdAt:
                    description: The date and time that the instance group manager
                      action was modified.
                    type: string
                  cronSpec:
                    description: The cron specification for a recurring scheduled
                      action. Actions can be applied a maximum of one time within
                      a 5 min period.
                    type: string
                  id:
                    type: string
                  instanceGroup:
                    description: instance group ID
                    type: string
                  instanceGroupManager:
                    description: Instance group manager ID of type scheduled
                    type: string
                  lastAppliedAt:
                    description: The date and time the scheduled action was last applied.
                      If empty the action has never been applied.
                    type: string
                  maxMembershipCount:
                    description: The maximum number of members in a managed instance
                      group
                    format: int64
                    type: integer
                  membershipCount:
                    description: The number of members the instance group should have
                      at the scheduled time.
                    format: int64
                    type: integer
                  minMembershipCount:
                    description: The minimum number of members in a managed instance
                      group
                    format: int64
                    type: integer
                  name:
                    description: instance group manager action name
                    type: string
                  nextRunAt:
                    description: The date and time the scheduled action will next
                      run. If empty the system is currently calculating the next run
                      time.
                    type: string
                  resourceType:
                    description: The resource type.
                    type: string
                  runAt:
                    description: The date and time the scheduled action will run.
                    type: string
                  status:
                    description: 'The status of the instance group action- `active`:
                      Action is ready to be run- `completed`: Action was completed
                      successfully- `failed`: Action could not be completed successfully-
                      `incompatible`: Action parameters are not compatible with the
                      group or manager- `omitted`: Action was not applied because
                      this action''s manager was disabled.'
                    type: string
                  targetManager:
                    description: The unique identifier for this instance group manager
                      of type autoscale.
                    type: string
                  targetManagerName:
                    description: Instance group manager name of type autoscale.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The date and time that the instance group manager
                      action was modified.
                    type: string
                required:
                - instanceGroup
                - instanceGroupManager
                type: object
              state:
                properties:
                  actionID:
                    description: Instance group manager action ID
                    type: string
                  actionType:
                    description: The type of action for the instance group.
                    type: string
                  autoDelete:
                    type: boolean
                  autoDeleteTimeout:
                    format: int64
                    type: integer
                  createdAt:
                    description: The date and time that the instance group manager
                      action was modified.
                    type: string
                  cronSpec:
                    description: The cron specification for a recurring scheduled
                      action. Actions can be applied a maximum of one time within
                      a 5 min period.
                    type: string
                  id:
                    type: string
                  instanceGroup:
                    description: instance group ID
                    type: string
                  instanceGroupManager:
                    description: Instance group manager ID of type scheduled
                    type: string
                  lastAppliedAt:
                    description: The date and time the scheduled action was last applied.
                      If empty the action has never been applied.
                    type: string
                  maxMembershipCount:
                    description: The maximum number of members in a managed instance
                      group
                    format: int64
                    type: integer
                  membershipCount:
                    description: The number of members the instance group should have
                      at the scheduled time.
                    format: int64
                    type: integer
                  minMembershipCount:
                    description: The minimum number of members in a managed instance
                      group
                    format: int64
                    type: integer
                  name:
                    description: instance group manager action name
                    type: string
                  nextRunAt:
                    description: The date and time the scheduled action will next
                      run. If empty the system is currently calculating the next run
                      time.
                    type: string
                  resourceType:
                    description: The resource type.
                    type: string
                  runAt:
                    description: The date and time the scheduled action will run.
                    type: string
                  status:
                    description: 'The status of the instance group action- `active`:
                      Action is ready to be run- `completed`: Action was completed
                      successfully- `failed`: Action could not be completed successfully-
                      `incompatible`: Action parameters are not compatible with the
                      group or manager- `omitted`: Action was not applied because
                      this action''s manager was disabled.'
                    type: string
                  targetManager:
                    description: The unique identifier for this instance group manager
                      of type autoscale.
                    type: string
                  targetManagerName:
                    description: Instance group manager name of type autoscale.
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The date and time that the instance group manager
                      action was modified.
                    type: string
                required:
                - instanceGroup
                - instanceGroupManager
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
