apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: subnets.is.ibm.kubeform.com
spec:
  group: is.ibm.kubeform.com
  names:
    kind: Subnet
    listKind: SubnetList
    plural: subnets
    singular: subnet
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  availableIpv4AddressCount:
                    description: The number of IPv4 addresses in this subnet that
                      are not in-use, and have not been reserved by the user or the
                      provider.
                    format: int64
                    type: integer
                  crn:
                    description: The crn of the resource
                    type: string
                  id:
                    type: string
                  ipVersion:
                    description: The IP version(s) to support for this subnet.
                    type: string
                  ipv4CIDRBlock:
                    description: IPV4 subnet - CIDR block
                    type: string
                  name:
                    description: Subnet name
                    type: string
                  networkACL:
                    description: The network ACL for this subnet
                    type: string
                  publicGateway:
                    description: Public Gateway of the subnet
                    type: string
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceCrn:
                    description: The crn of the resource
                    type: string
                  resourceGroup:
                    description: The resource group for this subnet
                    type: string
                  resourceGroupName:
                    description: The resource group name in which resource is provisioned
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  resourceStatus:
                    description: The status of the resource
                    type: string
                  routingTable:
                    description: routing table id that is associated with the subnet
                    type: string
                  status:
                    description: The status of the subnet
                    type: string
                  tags:
                    description: List of tags
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  totalIpv4AddressCount:
                    description: The total number of IPv4 addresses in this subnet.
                    format: int64
                    type: integer
                  vpc:
                    description: VPC instance ID
                    type: string
                  zone:
                    description: Subnet zone info
                    type: string
                required:
                - name
                - vpc
                - zone
                type: object
              state:
                properties:
                  availableIpv4AddressCount:
                    description: The number of IPv4 addresses in this subnet that
                      are not in-use, and have not been reserved by the user or the
                      provider.
                    format: int64
                    type: integer
                  crn:
                    description: The crn of the resource
                    type: string
                  id:
                    type: string
                  ipVersion:
                    description: The IP version(s) to support for this subnet.
                    type: string
                  ipv4CIDRBlock:
                    description: IPV4 subnet - CIDR block
                    type: string
                  name:
                    description: Subnet name
                    type: string
                  networkACL:
                    description: The network ACL for this subnet
                    type: string
                  publicGateway:
                    description: Public Gateway of the subnet
                    type: string
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceCrn:
                    description: The crn of the resource
                    type: string
                  resourceGroup:
                    description: The resource group for this subnet
                    type: string
                  resourceGroupName:
                    description: The resource group name in which resource is provisioned
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  resourceStatus:
                    description: The status of the resource
                    type: string
                  routingTable:
                    description: routing table id that is associated with the subnet
                    type: string
                  status:
                    description: The status of the subnet
                    type: string
                  tags:
                    description: List of tags
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  totalIpv4AddressCount:
                    description: The total number of IPv4 addresses in this subnet.
                    format: int64
                    type: integer
                  vpc:
                    description: VPC instance ID
                    type: string
                  zone:
                    description: Subnet zone info
                    type: string
                required:
                - name
                - vpc
                - zone
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
