apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: subnetnetworkaclattachments.is.ibm.kubeform.com
spec:
  group: is.ibm.kubeform.com
  names:
    kind: SubnetNetworkACLAttachment
    listKind: SubnetNetworkACLAttachmentList
    plural: subnetnetworkaclattachments
    singular: subnetnetworkaclattachment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  id:
                    type: string
                  name:
                    description: Network ACL name
                    type: string
                  networkACL:
                    description: The unique identifier of network ACL
                    type: string
                  resourceGroup:
                    description: Resource group ID for the network ACL
                    type: string
                  rules:
                    items:
                      properties:
                        ID:
                          description: The unique identifier for this Network ACL
                            rule
                          type: string
                        action:
                          description: Whether to allow or deny matching traffic
                          type: string
                        destination:
                          description: The destination CIDR block
                          type: string
                        direction:
                          description: Direction of traffic to enforce, either inbound
                            or outbound
                          type: string
                        icmp:
                          items:
                            properties:
                              code:
                                description: The ICMP traffic code to allow
                                format: int64
                                type: integer
                              type:
                                description: The ICMP traffic type to allow
                                format: int64
                                type: integer
                            type: object
                          type: array
                        ipVersion:
                          description: The IP version for this rule
                          type: string
                        name:
                          description: The user-defined name for this rule
                          type: string
                        source:
                          description: The source CIDR block
                          type: string
                        tcp:
                          items:
                            properties:
                              portMax:
                                description: The inclusive upper bound of TCP destination
                                  port range
                                format: int64
                                type: integer
                              portMin:
                                description: The inclusive lower bound of TCP destination
                                  port range
                                format: int64
                                type: integer
                              sourcePortMax:
                                description: The inclusive upper bound of TCP source
                                  port range
                                format: int64
                                type: integer
                              sourcePortMin:
                                description: The inclusive lower bound of TCP source
                                  port range
                                format: int64
                                type: integer
                            type: object
                          type: array
                        udp:
                          items:
                            properties:
                              portMax:
                                description: The inclusive upper bound of UDP destination
                                  port range
                                format: int64
                                type: integer
                              portMin:
                                description: The inclusive lower bound of UDP destination
                                  port range
                                format: int64
                                type: integer
                              sourcePortMax:
                                description: The inclusive upper bound of UDP source
                                  port range
                                format: int64
                                type: integer
                              sourcePortMin:
                                description: The inclusive lower bound of UDP source
                                  port range
                                format: int64
                                type: integer
                            type: object
                          type: array
                      type: object
                    type: array
                  subnet:
                    description: The subnet identifier
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  vpc:
                    description: Network ACL VPC
                    type: string
                required:
                - networkACL
                - subnet
                type: object
              state:
                properties:
                  id:
                    type: string
                  name:
                    description: Network ACL name
                    type: string
                  networkACL:
                    description: The unique identifier of network ACL
                    type: string
                  resourceGroup:
                    description: Resource group ID for the network ACL
                    type: string
                  rules:
                    items:
                      properties:
                        ID:
                          description: The unique identifier for this Network ACL
                            rule
                          type: string
                        action:
                          description: Whether to allow or deny matching traffic
                          type: string
                        destination:
                          description: The destination CIDR block
                          type: string
                        direction:
                          description: Direction of traffic to enforce, either inbound
                            or outbound
                          type: string
                        icmp:
                          items:
                            properties:
                              code:
                                description: The ICMP traffic code to allow
                                format: int64
                                type: integer
                              type:
                                description: The ICMP traffic type to allow
                                format: int64
                                type: integer
                            type: object
                          type: array
                        ipVersion:
                          description: The IP version for this rule
                          type: string
                        name:
                          description: The user-defined name for this rule
                          type: string
                        source:
                          description: The source CIDR block
                          type: string
                        tcp:
                          items:
                            properties:
                              portMax:
                                description: The inclusive upper bound of TCP destination
                                  port range
                                format: int64
                                type: integer
                              portMin:
                                description: The inclusive lower bound of TCP destination
                                  port range
                                format: int64
                                type: integer
                              sourcePortMax:
                                description: The inclusive upper bound of TCP source
                                  port range
                                format: int64
                                type: integer
                              sourcePortMin:
                                description: The inclusive lower bound of TCP source
                                  port range
                                format: int64
                                type: integer
                            type: object
                          type: array
                        udp:
                          items:
                            properties:
                              portMax:
                                description: The inclusive upper bound of UDP destination
                                  port range
                                format: int64
                                type: integer
                              portMin:
                                description: The inclusive lower bound of UDP destination
                                  port range
                                format: int64
                                type: integer
                              sourcePortMax:
                                description: The inclusive upper bound of UDP source
                                  port range
                                format: int64
                                type: integer
                              sourcePortMin:
                                description: The inclusive lower bound of UDP source
                                  port range
                                format: int64
                                type: integer
                            type: object
                          type: array
                      type: object
                    type: array
                  subnet:
                    description: The subnet identifier
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  vpc:
                    description: Network ACL VPC
                    type: string
                required:
                - networkACL
                - subnet
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
