apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instancegroupmemberships.is.ibm.kubeform.com
spec:
  group: is.ibm.kubeform.com
  names:
    kind: InstanceGroupMembership
    listKind: InstanceGroupMembershipList
    plural: instancegroupmemberships
    singular: instancegroupmembership
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  actionDelete:
                    description: The delete flag for this instance group membership.
                      Must be set to true to delete instance group membership.
                    type: boolean
                  deleteInstanceOnMembershipDelete:
                    description: If set to true, when deleting the membership the
                      instance will also be deleted.
                    type: boolean
                  id:
                    type: string
                  instance:
                    items:
                      properties:
                        crn:
                          description: The CRN for this virtual server instance.
                          type: string
                        name:
                          description: The user-defined name for this virtual server
                            instance (and default system hostname).
                          type: string
                        virtualServerInstance:
                          description: The unique identifier for this virtual server
                            instance.
                          type: string
                      type: object
                    type: array
                  instanceGroup:
                    description: The instance group identifier.
                    type: string
                  instanceGroupMembership:
                    description: The unique identifier for this instance group membership.
                    type: string
                  instanceTemplate:
                    items:
                      properties:
                        crn:
                          description: The CRN for this instance template.
                          type: string
                        instanceTemplate:
                          description: The unique identifier for this instance template.
                          type: string
                        name:
                          description: The unique user-defined name for this instance
                            template.
                          type: string
                      type: object
                    type: array
                  loadBalancerPoolMember:
                    description: The unique identifier for this load balancer pool
                      member.
                    type: string
                  name:
                    description: The user-defined name for this instance group membership.
                      Names must be unique within the instance group.
                    type: string
                  status:
                    description: 'The status of the instance group membership- `deleting`:
                      Membership is deleting dependent resources- `failed`: Membership
                      was unable to maintain dependent resources- `healthy`: Membership
                      is active and serving in the group- `pending`: Membership is
                      waiting for dependent resources- `unhealthy`: Membership has
                      unhealthy dependent resources.'
                    type: string
                required:
                - instanceGroup
                - instanceGroupMembership
                type: object
              state:
                properties:
                  actionDelete:
                    description: The delete flag for this instance group membership.
                      Must be set to true to delete instance group membership.
                    type: boolean
                  deleteInstanceOnMembershipDelete:
                    description: If set to true, when deleting the membership the
                      instance will also be deleted.
                    type: boolean
                  id:
                    type: string
                  instance:
                    items:
                      properties:
                        crn:
                          description: The CRN for this virtual server instance.
                          type: string
                        name:
                          description: The user-defined name for this virtual server
                            instance (and default system hostname).
                          type: string
                        virtualServerInstance:
                          description: The unique identifier for this virtual server
                            instance.
                          type: string
                      type: object
                    type: array
                  instanceGroup:
                    description: The instance group identifier.
                    type: string
                  instanceGroupMembership:
                    description: The unique identifier for this instance group membership.
                    type: string
                  instanceTemplate:
                    items:
                      properties:
                        crn:
                          description: The CRN for this instance template.
                          type: string
                        instanceTemplate:
                          description: The unique identifier for this instance template.
                          type: string
                        name:
                          description: The unique user-defined name for this instance
                            template.
                          type: string
                      type: object
                    type: array
                  loadBalancerPoolMember:
                    description: The unique identifier for this load balancer pool
                      member.
                    type: string
                  name:
                    description: The user-defined name for this instance group membership.
                      Names must be unique within the instance group.
                    type: string
                  status:
                    description: 'The status of the instance group membership- `deleting`:
                      Membership is deleting dependent resources- `failed`: Membership
                      was unable to maintain dependent resources- `healthy`: Membership
                      is active and serving in the group- `pending`: Membership is
                      waiting for dependent resources- `unhealthy`: Membership has
                      unhealthy dependent resources.'
                    type: string
                required:
                - instanceGroup
                - instanceGroupMembership
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
