apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: dedicatedhostgroups.is.ibm.kubeform.com
spec:
  group: is.ibm.kubeform.com
  names:
    kind: DedicatedHostGroup
    listKind: DedicatedHostGroupList
    plural: dedicatedhostgroups
    singular: dedicatedhostgroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  class:
                    description: The dedicated host profile class for hosts in this
                      group.
                    type: string
                  createdAt:
                    description: The date and time that the dedicated host group was
                      created.
                    type: string
                  crn:
                    description: The CRN for this dedicated host group.
                    type: string
                  dedicatedHosts:
                    description: The dedicated hosts that are in this dedicated host
                      group.
                    items:
                      properties:
                        ID:
                          description: The unique identifier for this dedicated host.
                          type: string
                        crn:
                          description: The CRN for this dedicated host.
                          type: string
                        deleted:
                          description: If present, this property indicates the referenced
                            resource has been deleted and providessome supplementary
                            information.
                          items:
                            properties:
                              moreInfo:
                                description: Link to documentation about deleted resources.
                                type: string
                            type: object
                          type: array
                        href:
                          description: The URL for this dedicated host.
                          type: string
                        name:
                          description: The unique user-defined name for this dedicated
                            host. If unspecified, the name will be a hyphenated list
                            of randomly-selected words.
                          type: string
                        resourceType:
                          description: The type of resource referenced.
                          type: string
                      type: object
                    type: array
                  family:
                    description: The dedicated host profile family for hosts in this
                      group.
                    type: string
                  href:
                    description: The URL for this dedicated host group.
                    type: string
                  id:
                    type: string
                  name:
                    description: The unique user-defined name for this dedicated host
                      group. If unspecified, the name will be a hyphenated list of
                      randomly-selected words.
                    type: string
                  resourceGroup:
                    description: The unique identifier of the resource group to use.
                      If unspecified, the account's [default resourcegroup](https://cloud.ibm.com/apidocs/resource-manager#introduction)
                      is used.
                    type: string
                  resourceType:
                    description: The type of resource referenced.
                    type: string
                  supportedInstanceProfiles:
                    description: Array of instance profiles that can be used by instances
                      placed on this dedicated host group.
                    items:
                      properties:
                        href:
                          description: The URL for this virtual server instance profile.
                          type: string
                        name:
                          description: The globally unique name for this virtual server
                            instance profile.
                          type: string
                      type: object
                    type: array
                  zone:
                    description: The globally unique name of the zone this dedicated
                      host group will reside in.
                    type: string
                required:
                - class
                - family
                - zone
                type: object
              state:
                properties:
                  class:
                    description: The dedicated host profile class for hosts in this
                      group.
                    type: string
                  createdAt:
                    description: The date and time that the dedicated host group was
                      created.
                    type: string
                  crn:
                    description: The CRN for this dedicated host group.
                    type: string
                  dedicatedHosts:
                    description: The dedicated hosts that are in this dedicated host
                      group.
                    items:
                      properties:
                        ID:
                          description: The unique identifier for this dedicated host.
                          type: string
                        crn:
                          description: The CRN for this dedicated host.
                          type: string
                        deleted:
                          description: If present, this property indicates the referenced
                            resource has been deleted and providessome supplementary
                            information.
                          items:
                            properties:
                              moreInfo:
                                description: Link to documentation about deleted resources.
                                type: string
                            type: object
                          type: array
                        href:
                          description: The URL for this dedicated host.
                          type: string
                        name:
                          description: The unique user-defined name for this dedicated
                            host. If unspecified, the name will be a hyphenated list
                            of randomly-selected words.
                          type: string
                        resourceType:
                          description: The type of resource referenced.
                          type: string
                      type: object
                    type: array
                  family:
                    description: The dedicated host profile family for hosts in this
                      group.
                    type: string
                  href:
                    description: The URL for this dedicated host group.
                    type: string
                  id:
                    type: string
                  name:
                    description: The unique user-defined name for this dedicated host
                      group. If unspecified, the name will be a hyphenated list of
                      randomly-selected words.
                    type: string
                  resourceGroup:
                    description: The unique identifier of the resource group to use.
                      If unspecified, the account's [default resourcegroup](https://cloud.ibm.com/apidocs/resource-manager#introduction)
                      is used.
                    type: string
                  resourceType:
                    description: The type of resource referenced.
                    type: string
                  supportedInstanceProfiles:
                    description: Array of instance profiles that can be used by instances
                      placed on this dedicated host group.
                    items:
                      properties:
                        href:
                          description: The URL for this virtual server instance profile.
                          type: string
                        name:
                          description: The globally unique name for this virtual server
                            instance profile.
                          type: string
                      type: object
                    type: array
                  zone:
                    description: The globally unique name of the zone this dedicated
                      host group will reside in.
                    type: string
                required:
                - class
                - family
                - zone
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
