apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: lbaas.lbaas.ibm.kubeform.com
spec:
  group: lbaas.ibm.kubeform.com
  names:
    kind: Lbaas
    listKind: LbaasList
    plural: lbaas
    singular: lbaas
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  datacenter:
                    type: string
                  description:
                    description: Description of a load balancer.
                    type: string
                  healthMonitors:
                    items:
                      properties:
                        interval:
                          format: int64
                          type: integer
                        maxRetries:
                          format: int64
                          type: integer
                        monitorID:
                          type: string
                        port:
                          format: int64
                          type: integer
                        protocol:
                          type: string
                        timeout:
                          format: int64
                          type: integer
                        urlPath:
                          type: string
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: The load balancer's name.
                    type: string
                  protocols:
                    description: Protocols to be assigned to this load balancer.
                    items:
                      properties:
                        backendPort:
                          description: Backend Protocol port number. Should be in
                            range (1, 65535)
                          format: int64
                          type: integer
                        backendProtocol:
                          description: Backend protocol, one of 'TCP', 'HTTP', 'HTTPS'.
                          type: string
                        frontendPort:
                          description: Frontend Protocol port number. Should be in
                            range (1, 65535)
                          format: int64
                          type: integer
                        frontendProtocol:
                          description: Frontend protocol, one of 'TCP', 'HTTP', 'HTTPS'.
                          type: string
                        loadBalancingMethod:
                          description: 'Load balancing algorithm: ''round_robin'',
                            ''weighted_round_robin'', ''least_connection'''
                          type: string
                        maxConn:
                          description: No. of connections the listener can accept.
                            Should be between 1-64000
                          format: int64
                          type: integer
                        protocolID:
                          description: The UUID of a load balancer protocol
                          type: string
                        sessionStickiness:
                          description: Session stickness. Valid values is SOURCE_IP
                            and HTTP_COOKIE
                          type: string
                        tlsCertificateID:
                          description: This references to SSL/TLS certificate for
                            a protocol
                          format: int64
                          type: integer
                      required:
                      - backendPort
                      - backendProtocol
                      - frontendPort
                      - frontendProtocol
                      type: object
                    type: array
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  resourceStatus:
                    description: The status of the resource
                    type: string
                  sslCiphers:
                    items:
                      type: string
                    type: array
                  status:
                    description: The operation status 'ONLINE' or 'OFFLINE' of a load
                      balancer.
                    type: string
                  subnets:
                    description: The subnet where this Load Balancer will be provisioned.
                    items:
                      format: int64
                      type: integer
                    type: array
                  type:
                    description: Specifies if a load balancer is public or private
                    type: string
                  useSystemPublicIPPool:
                    description: '"in public loadbalancer - Public IP address allocation
                      done by system public IP pool or public subnet."'
                    type: boolean
                  vip:
                    description: The virtual ip address of this load balancer
                    type: string
                  waitTimeMinutes:
                    format: int64
                    type: integer
                required:
                - name
                - subnets
                type: object
              state:
                properties:
                  datacenter:
                    type: string
                  description:
                    description: Description of a load balancer.
                    type: string
                  healthMonitors:
                    items:
                      properties:
                        interval:
                          format: int64
                          type: integer
                        maxRetries:
                          format: int64
                          type: integer
                        monitorID:
                          type: string
                        port:
                          format: int64
                          type: integer
                        protocol:
                          type: string
                        timeout:
                          format: int64
                          type: integer
                        urlPath:
                          type: string
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: The load balancer's name.
                    type: string
                  protocols:
                    description: Protocols to be assigned to this load balancer.
                    items:
                      properties:
                        backendPort:
                          description: Backend Protocol port number. Should be in
                            range (1, 65535)
                          format: int64
                          type: integer
                        backendProtocol:
                          description: Backend protocol, one of 'TCP', 'HTTP', 'HTTPS'.
                          type: string
                        frontendPort:
                          description: Frontend Protocol port number. Should be in
                            range (1, 65535)
                          format: int64
                          type: integer
                        frontendProtocol:
                          description: Frontend protocol, one of 'TCP', 'HTTP', 'HTTPS'.
                          type: string
                        loadBalancingMethod:
                          description: 'Load balancing algorithm: ''round_robin'',
                            ''weighted_round_robin'', ''least_connection'''
                          type: string
                        maxConn:
                          description: No. of connections the listener can accept.
                            Should be between 1-64000
                          format: int64
                          type: integer
                        protocolID:
                          description: The UUID of a load balancer protocol
                          type: string
                        sessionStickiness:
                          description: Session stickness. Valid values is SOURCE_IP
                            and HTTP_COOKIE
                          type: string
                        tlsCertificateID:
                          description: This references to SSL/TLS certificate for
                            a protocol
                          format: int64
                          type: integer
                      required:
                      - backendPort
                      - backendProtocol
                      - frontendPort
                      - frontendProtocol
                      type: object
                    type: array
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  resourceStatus:
                    description: The status of the resource
                    type: string
                  sslCiphers:
                    items:
                      type: string
                    type: array
                  status:
                    description: The operation status 'ONLINE' or 'OFFLINE' of a load
                      balancer.
                    type: string
                  subnets:
                    description: The subnet where this Load Balancer will be provisioned.
                    items:
                      format: int64
                      type: integer
                    type: array
                  type:
                    description: Specifies if a load balancer is public or private
                    type: string
                  useSystemPublicIPPool:
                    description: '"in public loadbalancer - Public IP address allocation
                      done by system public IP pool or public subnet."'
                    type: boolean
                  vip:
                    description: The virtual ip address of this load balancer
                    type: string
                  waitTimeMinutes:
                    format: int64
                    type: integer
                required:
                - name
                - subnets
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
