apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: gateways.network.ibm.kubeform.com
spec:
  group: network.ibm.kubeform.com
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  associatedVlans:
                    description: The VLAN instances associated with this Network Gateway
                    items:
                      properties:
                        bypass:
                          description: Indicates if the VLAN is in bypass or routed
                            modes
                          type: boolean
                        networkVLANID:
                          description: The Identifier of the VLAN which is associated
                          format: int64
                          type: integer
                        vlanID:
                          format: int64
                          type: integer
                      type: object
                    type: array
                  id:
                    type: string
                  members:
                    description: The hardware members of this network Gateway
                    items:
                      properties:
                        datacenter:
                          type: string
                        diskKeyNames:
                          items:
                            type: string
                          type: array
                        domain:
                          type: string
                        hostname:
                          type: string
                        ipv6Address:
                          type: string
                        ipv6Enabled:
                          type: boolean
                        memberID:
                          format: int64
                          type: integer
                        memory:
                          format: int64
                          type: integer
                        networkSpeed:
                          format: int64
                          type: integer
                        notes:
                          type: string
                        osKeyName:
                          type: string
                        packageKeyName:
                          type: string
                        postInstallScriptURI:
                          type: string
                        privateIpv4Address:
                          type: string
                        privateNetworkOnly:
                          type: boolean
                        privateVLANID:
                          format: int64
                          type: integer
                        processKeyName:
                          type: string
                        publicBandwidth:
                          format: int64
                          type: integer
                        publicIpv4Address:
                          type: string
                        publicVLANID:
                          format: int64
                          type: integer
                        redundantNetwork:
                          type: boolean
                        redundantPowerSupply:
                          type: boolean
                        sshKeyIDS:
                          items:
                            format: int64
                            type: integer
                          type: array
                        storageGroups:
                          items:
                            properties:
                              arraySize:
                                format: int64
                                type: integer
                              arrayTypeID:
                                format: int64
                                type: integer
                              hardDrives:
                                items:
                                  format: int64
                                  type: integer
                                type: array
                              partitionTemplateID:
                                format: int64
                                type: integer
                            required:
                            - arrayTypeID
                            - hardDrives
                            type: object
                          type: array
                        tags:
                          items:
                            type: string
                          type: array
                        tcpMonitoring:
                          type: boolean
                        unbondedNetwork:
                          type: boolean
                        userMetadata:
                          type: string
                      required:
                      - datacenter
                      - domain
                      - memory
                      type: object
                    maxItems: 2
                    minItems: 1
                    type: array
                  name:
                    description: The name of the gateway
                    type: string
                  postInstallScriptURI:
                    type: string
                  privateIPAddressID:
                    format: int64
                    type: integer
                  privateIpv4Address:
                    type: string
                  privateVLANID:
                    format: int64
                    type: integer
                  publicIPAddressID:
                    format: int64
                    type: integer
                  publicIpv4Address:
                    type: string
                  publicIpv6AddressID:
                    format: int64
                    type: integer
                  publicVLANID:
                    format: int64
                    type: integer
                  sshKeyIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  status:
                    type: string
                required:
                - members
                - name
                type: object
              state:
                properties:
                  associatedVlans:
                    description: The VLAN instances associated with this Network Gateway
                    items:
                      properties:
                        bypass:
                          description: Indicates if the VLAN is in bypass or routed
                            modes
                          type: boolean
                        networkVLANID:
                          description: The Identifier of the VLAN which is associated
                          format: int64
                          type: integer
                        vlanID:
                          format: int64
                          type: integer
                      type: object
                    type: array
                  id:
                    type: string
                  members:
                    description: The hardware members of this network Gateway
                    items:
                      properties:
                        datacenter:
                          type: string
                        diskKeyNames:
                          items:
                            type: string
                          type: array
                        domain:
                          type: string
                        hostname:
                          type: string
                        ipv6Address:
                          type: string
                        ipv6Enabled:
                          type: boolean
                        memberID:
                          format: int64
                          type: integer
                        memory:
                          format: int64
                          type: integer
                        networkSpeed:
                          format: int64
                          type: integer
                        notes:
                          type: string
                        osKeyName:
                          type: string
                        packageKeyName:
                          type: string
                        postInstallScriptURI:
                          type: string
                        privateIpv4Address:
                          type: string
                        privateNetworkOnly:
                          type: boolean
                        privateVLANID:
                          format: int64
                          type: integer
                        processKeyName:
                          type: string
                        publicBandwidth:
                          format: int64
                          type: integer
                        publicIpv4Address:
                          type: string
                        publicVLANID:
                          format: int64
                          type: integer
                        redundantNetwork:
                          type: boolean
                        redundantPowerSupply:
                          type: boolean
                        sshKeyIDS:
                          items:
                            format: int64
                            type: integer
                          type: array
                        storageGroups:
                          items:
                            properties:
                              arraySize:
                                format: int64
                                type: integer
                              arrayTypeID:
                                format: int64
                                type: integer
                              hardDrives:
                                items:
                                  format: int64
                                  type: integer
                                type: array
                              partitionTemplateID:
                                format: int64
                                type: integer
                            required:
                            - arrayTypeID
                            - hardDrives
                            type: object
                          type: array
                        tags:
                          items:
                            type: string
                          type: array
                        tcpMonitoring:
                          type: boolean
                        unbondedNetwork:
                          type: boolean
                        userMetadata:
                          type: string
                      required:
                      - datacenter
                      - domain
                      - memory
                      type: object
                    maxItems: 2
                    minItems: 1
                    type: array
                  name:
                    description: The name of the gateway
                    type: string
                  postInstallScriptURI:
                    type: string
                  privateIPAddressID:
                    format: int64
                    type: integer
                  privateIpv4Address:
                    type: string
                  privateVLANID:
                    format: int64
                    type: integer
                  publicIPAddressID:
                    format: int64
                    type: integer
                  publicIpv4Address:
                    type: string
                  publicIpv6AddressID:
                    format: int64
                    type: integer
                  publicVLANID:
                    format: int64
                    type: integer
                  sshKeyIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  status:
                    type: string
                required:
                - members
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
