apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: clusters.satellite.ibm.kubeform.com
spec:
  group: satellite.ibm.kubeform.com
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  crn:
                    description: CRN of resource instance
                    type: string
                  defaultWorkerPoolLabels:
                    additionalProperties:
                      type: string
                    description: Labels on the default worker pool
                    type: object
                  disablePublicServiceEndpoint:
                    description: Boolean value true if Public service endpoint to
                      be disabled
                    type: boolean
                  enableConfigAdmin:
                    description: Grant cluster admin access to Satellite Config to
                      manage Kubernetes resources.
                    type: boolean
                  hostLabels:
                    description: Labels that describe a Satellite host for default
                      workerpool
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  ingressHostname:
                    type: string
                  kubeVersion:
                    description: The OpenShift Container Platform version
                    type: string
                  location:
                    description: The name or ID of the Satellite location
                    type: string
                  masterStatus:
                    type: string
                  masterURL:
                    type: string
                  name:
                    description: The unique name for the new IBM Cloud Satellite cluster
                    type: string
                  patchVersion:
                    description: Kubernetes patch version
                    type: string
                  podSubnet:
                    description: User provided value for the pod subnet
                    type: string
                  privateServiceEndpointEnabled:
                    type: boolean
                  privateServiceEndpointURL:
                    type: string
                  publicServiceEndpointEnabled:
                    type: boolean
                  publicServiceEndpointURL:
                    type: string
                  pullSecret:
                    description: The RedHat pull secret to create the OpenShift cluster
                    type: string
                  resourceGroupID:
                    description: ID of the resource group.
                    type: string
                  resourceGroupName:
                    description: The resource group name in which resource is provisioned
                    type: string
                  retryPatchVersion:
                    description: Argument which helps to retry the patch version updates
                      on worker nodes. Increment the value to retry the patch updates
                      if the previous apply fails
                    format: int64
                    type: integer
                  serviceSubnet:
                    description: User provided value for service subnet
                    type: string
                  state:
                    description: The lifecycle state of the cluster.
                    type: string
                  tags:
                    description: List of tags for the resources
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  waitForWorkerUpdate:
                    description: Wait for worker node to update during kube version
                      update.
                    type: boolean
                  workerCount:
                    description: 'The number of worker nodes per zone in the default
                      worker pool. Required when ''--host-label'' is specified. (default:
                      0)'
                    format: int64
                    type: integer
                  zones:
                    description: Zone info for worker pool
                    items:
                      properties:
                        ID:
                          description: Zone for the worker pool in a multizone cluster
                          type: string
                      required:
                      - ID
                      type: object
                    type: array
                required:
                - location
                - name
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  crn:
                    description: CRN of resource instance
                    type: string
                  defaultWorkerPoolLabels:
                    additionalProperties:
                      type: string
                    description: Labels on the default worker pool
                    type: object
                  disablePublicServiceEndpoint:
                    description: Boolean value true if Public service endpoint to
                      be disabled
                    type: boolean
                  enableConfigAdmin:
                    description: Grant cluster admin access to Satellite Config to
                      manage Kubernetes resources.
                    type: boolean
                  hostLabels:
                    description: Labels that describe a Satellite host for default
                      workerpool
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  ingressHostname:
                    type: string
                  kubeVersion:
                    description: The OpenShift Container Platform version
                    type: string
                  location:
                    description: The name or ID of the Satellite location
                    type: string
                  masterStatus:
                    type: string
                  masterURL:
                    type: string
                  name:
                    description: The unique name for the new IBM Cloud Satellite cluster
                    type: string
                  patchVersion:
                    description: Kubernetes patch version
                    type: string
                  podSubnet:
                    description: User provided value for the pod subnet
                    type: string
                  privateServiceEndpointEnabled:
                    type: boolean
                  privateServiceEndpointURL:
                    type: string
                  publicServiceEndpointEnabled:
                    type: boolean
                  publicServiceEndpointURL:
                    type: string
                  pullSecret:
                    description: The RedHat pull secret to create the OpenShift cluster
                    type: string
                  resourceGroupID:
                    description: ID of the resource group.
                    type: string
                  resourceGroupName:
                    description: The resource group name in which resource is provisioned
                    type: string
                  retryPatchVersion:
                    description: Argument which helps to retry the patch version updates
                      on worker nodes. Increment the value to retry the patch updates
                      if the previous apply fails
                    format: int64
                    type: integer
                  serviceSubnet:
                    description: User provided value for service subnet
                    type: string
                  state:
                    description: The lifecycle state of the cluster.
                    type: string
                  tags:
                    description: List of tags for the resources
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  waitForWorkerUpdate:
                    description: Wait for worker node to update during kube version
                      update.
                    type: boolean
                  workerCount:
                    description: 'The number of worker nodes per zone in the default
                      worker pool. Required when ''--host-label'' is specified. (default:
                      0)'
                    format: int64
                    type: integer
                  zones:
                    description: Zone info for worker pool
                    items:
                      properties:
                        ID:
                          description: Zone for the worker pool in a multizone cluster
                          type: string
                      required:
                      - ID
                      type: object
                    type: array
                required:
                - location
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
