apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: blocks.storage.ibm.kubeform.com
spec:
  group: storage.ibm.kubeform.com
  names:
    kind: Block
    listKind: BlockList
    plural: blocks
    singular: block
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  allowedHardwareIDS:
                    description: List of allowe hardware IDs
                    items:
                      format: int64
                      type: integer
                    type: array
                  allowedHardwareInfo:
                    description: Deprecated
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  allowedHostInfo:
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  allowedIPAddresses:
                    description: Allowed IP addresses
                    items:
                      type: string
                    type: array
                  allowedVirtualGuestIDS:
                    description: List of allowed virtual guest IDs
                    items:
                      format: int64
                      type: integer
                    type: array
                  allowedVirtualGuestInfo:
                    description: Deprecated
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  capacity:
                    description: Storage block size
                    format: int64
                    type: integer
                  datacenter:
                    description: Datacenter name
                    type: string
                  hostname:
                    description: Hostname
                    type: string
                  hourlyBilling:
                    description: Billing done hourly, if set to true
                    type: boolean
                  id:
                    type: string
                  iops:
                    description: IOPS value required
                    format: double
                    type: number
                  lunid:
                    description: LUN Id
                    type: string
                  notes:
                    description: Additional note info
                    type: string
                  osFormatType:
                    description: OS formatr type
                    type: string
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  snapshotCapacity:
                    description: Snapshot capacity in GB
                    format: int64
                    type: integer
                  tags:
                    description: List of tags associated with the resource
                    items:
                      type: string
                    type: array
                  targetAddress:
                    description: List of target Addresses
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  type:
                    description: Storage block type
                    type: string
                  volumename:
                    description: Volume name
                    type: string
                required:
                - capacity
                - datacenter
                - iops
                - osFormatType
                - type
                type: object
              state:
                properties:
                  allowedHardwareIDS:
                    description: List of allowe hardware IDs
                    items:
                      format: int64
                      type: integer
                    type: array
                  allowedHardwareInfo:
                    description: Deprecated
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  allowedHostInfo:
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  allowedIPAddresses:
                    description: Allowed IP addresses
                    items:
                      type: string
                    type: array
                  allowedVirtualGuestIDS:
                    description: List of allowed virtual guest IDs
                    items:
                      format: int64
                      type: integer
                    type: array
                  allowedVirtualGuestInfo:
                    description: Deprecated
                    items:
                      properties:
                        ID:
                          format: int64
                          type: integer
                        hostIqn:
                          type: string
                        password:
                          type: string
                        username:
                          type: string
                      type: object
                    type: array
                  capacity:
                    description: Storage block size
                    format: int64
                    type: integer
                  datacenter:
                    description: Datacenter name
                    type: string
                  hostname:
                    description: Hostname
                    type: string
                  hourlyBilling:
                    description: Billing done hourly, if set to true
                    type: boolean
                  id:
                    type: string
                  iops:
                    description: IOPS value required
                    format: double
                    type: number
                  lunid:
                    description: LUN Id
                    type: string
                  notes:
                    description: Additional note info
                    type: string
                  osFormatType:
                    description: OS formatr type
                    type: string
                  resourceControllerURL:
                    description: The URL of the IBM Cloud dashboard that can be used
                      to explore and view details about this instance
                    type: string
                  resourceName:
                    description: The name of the resource
                    type: string
                  snapshotCapacity:
                    description: Snapshot capacity in GB
                    format: int64
                    type: integer
                  tags:
                    description: List of tags associated with the resource
                    items:
                      type: string
                    type: array
                  targetAddress:
                    description: List of target Addresses
                    items:
                      type: string
                    type: array
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  type:
                    description: Storage block type
                    type: string
                  volumename:
                    description: Volume name
                    type: string
                required:
                - capacity
                - datacenter
                - iops
                - osFormatType
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
