apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ibm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: connections.tg.ibm.kubeform.com
spec:
  group: tg.ibm.kubeform.com
  names:
    kind: Connection
    listKind: ConnectionList
    plural: connections
    singular: connection
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  baseConnectionID:
                    description: The ID of a network_type 'classic' connection a tunnel
                      is configured over. This field only applies to network type
                      'gre_tunnel' connections.
                    type: string
                  connectionID:
                    description: The Transit Gateway Connection identifier
                    type: string
                  createdAt:
                    description: The date and time that this connection was created
                    type: string
                  gateway:
                    description: The Transit Gateway identifier
                    type: string
                  id:
                    type: string
                  localGatewayIP:
                    description: The local gateway IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  localTunnelIP:
                    description: The local tunnel IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  name:
                    description: The user-defined name for this transit gateway. If
                      unspecified, the name will be the network name (the name of
                      the VPC in the case of network type 'vpc', and the word Classic,
                      in the case of network type 'classic').
                    type: string
                  networkAccountID:
                    description: The ID of the account which owns the network that
                      is being connected. Generally only used if the network is in
                      a different account than the gateway.
                    type: string
                  networkID:
                    description: The ID of the network being connected via this connection.
                      This field is required for some types, such as 'vpc'. For network
                      type 'vpc' this is the CRN of the VPC to be connected. This
                      field is required to be unspecified for network type 'classic'.
                    type: string
                  networkType:
                    description: Defines what type of network is connected via this
                      connection.Allowable values (classic,vpc,gre_tunnel)
                    type: string
                  relatedCrn:
                    description: The crn of the transit gateway
                    type: string
                  remoteBGPAsn:
                    description: The remote network BGP ASN. This field only applies
                      to network type 'gre_tunnel' connections.
                    format: int64
                    type: integer
                  remoteGatewayIP:
                    description: The remote gateway IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  remoteTunnelIP:
                    description: The remote tunnel IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  requestStatus:
                    description: 'Only visible for cross account connections, this
                      field represents the status of the request to connect the given
                      network between accounts.Possible values: [pending,approved,rejected,expired,detached]'
                    type: string
                  status:
                    description: 'What is the current configuration state of this
                      connection. Possible values: [attached,failed,pending,deleting,detaching,detached]'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The date and time that this connection was last updated
                    type: string
                  zone:
                    description: Location of GRE tunnel. This field only applies to
                      network type 'gre_tunnel' connections.
                    type: string
                required:
                - gateway
                - networkType
                type: object
              state:
                properties:
                  baseConnectionID:
                    description: The ID of a network_type 'classic' connection a tunnel
                      is configured over. This field only applies to network type
                      'gre_tunnel' connections.
                    type: string
                  connectionID:
                    description: The Transit Gateway Connection identifier
                    type: string
                  createdAt:
                    description: The date and time that this connection was created
                    type: string
                  gateway:
                    description: The Transit Gateway identifier
                    type: string
                  id:
                    type: string
                  localGatewayIP:
                    description: The local gateway IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  localTunnelIP:
                    description: The local tunnel IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  name:
                    description: The user-defined name for this transit gateway. If
                      unspecified, the name will be the network name (the name of
                      the VPC in the case of network type 'vpc', and the word Classic,
                      in the case of network type 'classic').
                    type: string
                  networkAccountID:
                    description: The ID of the account which owns the network that
                      is being connected. Generally only used if the network is in
                      a different account than the gateway.
                    type: string
                  networkID:
                    description: The ID of the network being connected via this connection.
                      This field is required for some types, such as 'vpc'. For network
                      type 'vpc' this is the CRN of the VPC to be connected. This
                      field is required to be unspecified for network type 'classic'.
                    type: string
                  networkType:
                    description: Defines what type of network is connected via this
                      connection.Allowable values (classic,vpc,gre_tunnel)
                    type: string
                  relatedCrn:
                    description: The crn of the transit gateway
                    type: string
                  remoteBGPAsn:
                    description: The remote network BGP ASN. This field only applies
                      to network type 'gre_tunnel' connections.
                    format: int64
                    type: integer
                  remoteGatewayIP:
                    description: The remote gateway IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  remoteTunnelIP:
                    description: The remote tunnel IP address. This field only applies
                      to network type 'gre_tunnel' connections.
                    type: string
                  requestStatus:
                    description: 'Only visible for cross account connections, this
                      field represents the status of the request to connect the given
                      network between accounts.Possible values: [pending,approved,rejected,expired,detached]'
                    type: string
                  status:
                    description: 'What is the current configuration state of this
                      connection. Possible values: [attached,failed,pending,deleting,detaching,detached]'
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  updatedAt:
                    description: The date and time that this connection was last updated
                    type: string
                  zone:
                    description: Location of GRE tunnel. This field only applies to
                      network type 'gre_tunnel' connections.
                    type: string
                required:
                - gateway
                - networkType
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
