/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/is/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVpcAddressPrefixes implements VpcAddressPrefixInterface
type FakeVpcAddressPrefixes struct {
	Fake *FakeIsV1alpha1
	ns   string
}

var vpcaddressprefixesResource = schema.GroupVersionResource{Group: "is.ibm.kubeform.com", Version: "v1alpha1", Resource: "vpcaddressprefixes"}

var vpcaddressprefixesKind = schema.GroupVersionKind{Group: "is.ibm.kubeform.com", Version: "v1alpha1", Kind: "VpcAddressPrefix"}

// Get takes name of the vpcAddressPrefix, and returns the corresponding vpcAddressPrefix object, and an error if there is any.
func (c *FakeVpcAddressPrefixes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VpcAddressPrefix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vpcaddressprefixesResource, c.ns, name), &v1alpha1.VpcAddressPrefix{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VpcAddressPrefix), err
}

// List takes label and field selectors, and returns the list of VpcAddressPrefixes that match those selectors.
func (c *FakeVpcAddressPrefixes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VpcAddressPrefixList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vpcaddressprefixesResource, vpcaddressprefixesKind, c.ns, opts), &v1alpha1.VpcAddressPrefixList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VpcAddressPrefixList{ListMeta: obj.(*v1alpha1.VpcAddressPrefixList).ListMeta}
	for _, item := range obj.(*v1alpha1.VpcAddressPrefixList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vpcAddressPrefixes.
func (c *FakeVpcAddressPrefixes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vpcaddressprefixesResource, c.ns, opts))

}

// Create takes the representation of a vpcAddressPrefix and creates it.  Returns the server's representation of the vpcAddressPrefix, and an error, if there is any.
func (c *FakeVpcAddressPrefixes) Create(ctx context.Context, vpcAddressPrefix *v1alpha1.VpcAddressPrefix, opts v1.CreateOptions) (result *v1alpha1.VpcAddressPrefix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vpcaddressprefixesResource, c.ns, vpcAddressPrefix), &v1alpha1.VpcAddressPrefix{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VpcAddressPrefix), err
}

// Update takes the representation of a vpcAddressPrefix and updates it. Returns the server's representation of the vpcAddressPrefix, and an error, if there is any.
func (c *FakeVpcAddressPrefixes) Update(ctx context.Context, vpcAddressPrefix *v1alpha1.VpcAddressPrefix, opts v1.UpdateOptions) (result *v1alpha1.VpcAddressPrefix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vpcaddressprefixesResource, c.ns, vpcAddressPrefix), &v1alpha1.VpcAddressPrefix{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VpcAddressPrefix), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVpcAddressPrefixes) UpdateStatus(ctx context.Context, vpcAddressPrefix *v1alpha1.VpcAddressPrefix, opts v1.UpdateOptions) (*v1alpha1.VpcAddressPrefix, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vpcaddressprefixesResource, "status", c.ns, vpcAddressPrefix), &v1alpha1.VpcAddressPrefix{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VpcAddressPrefix), err
}

// Delete takes name of the vpcAddressPrefix and deletes it. Returns an error if one occurs.
func (c *FakeVpcAddressPrefixes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vpcaddressprefixesResource, c.ns, name), &v1alpha1.VpcAddressPrefix{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVpcAddressPrefixes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vpcaddressprefixesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VpcAddressPrefixList{})
	return err
}

// Patch applies the patch and returns the patched vpcAddressPrefix.
func (c *FakeVpcAddressPrefixes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VpcAddressPrefix, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vpcaddressprefixesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VpcAddressPrefix{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VpcAddressPrefix), err
}
