/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/is/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLbPoolMembers implements LbPoolMemberInterface
type FakeLbPoolMembers struct {
	Fake *FakeIsV1alpha1
	ns   string
}

var lbpoolmembersResource = schema.GroupVersionResource{Group: "is.ibm.kubeform.com", Version: "v1alpha1", Resource: "lbpoolmembers"}

var lbpoolmembersKind = schema.GroupVersionKind{Group: "is.ibm.kubeform.com", Version: "v1alpha1", Kind: "LbPoolMember"}

// Get takes name of the lbPoolMember, and returns the corresponding lbPoolMember object, and an error if there is any.
func (c *FakeLbPoolMembers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LbPoolMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(lbpoolmembersResource, c.ns, name), &v1alpha1.LbPoolMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LbPoolMember), err
}

// List takes label and field selectors, and returns the list of LbPoolMembers that match those selectors.
func (c *FakeLbPoolMembers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LbPoolMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(lbpoolmembersResource, lbpoolmembersKind, c.ns, opts), &v1alpha1.LbPoolMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LbPoolMemberList{ListMeta: obj.(*v1alpha1.LbPoolMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.LbPoolMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lbPoolMembers.
func (c *FakeLbPoolMembers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(lbpoolmembersResource, c.ns, opts))

}

// Create takes the representation of a lbPoolMember and creates it.  Returns the server's representation of the lbPoolMember, and an error, if there is any.
func (c *FakeLbPoolMembers) Create(ctx context.Context, lbPoolMember *v1alpha1.LbPoolMember, opts v1.CreateOptions) (result *v1alpha1.LbPoolMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(lbpoolmembersResource, c.ns, lbPoolMember), &v1alpha1.LbPoolMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LbPoolMember), err
}

// Update takes the representation of a lbPoolMember and updates it. Returns the server's representation of the lbPoolMember, and an error, if there is any.
func (c *FakeLbPoolMembers) Update(ctx context.Context, lbPoolMember *v1alpha1.LbPoolMember, opts v1.UpdateOptions) (result *v1alpha1.LbPoolMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(lbpoolmembersResource, c.ns, lbPoolMember), &v1alpha1.LbPoolMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LbPoolMember), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLbPoolMembers) UpdateStatus(ctx context.Context, lbPoolMember *v1alpha1.LbPoolMember, opts v1.UpdateOptions) (*v1alpha1.LbPoolMember, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(lbpoolmembersResource, "status", c.ns, lbPoolMember), &v1alpha1.LbPoolMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LbPoolMember), err
}

// Delete takes name of the lbPoolMember and deletes it. Returns an error if one occurs.
func (c *FakeLbPoolMembers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(lbpoolmembersResource, c.ns, name), &v1alpha1.LbPoolMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLbPoolMembers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(lbpoolmembersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LbPoolMemberList{})
	return err
}

// Patch applies the patch and returns the patched lbPoolMember.
func (c *FakeLbPoolMembers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LbPoolMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(lbpoolmembersResource, c.ns, name, pt, data, subresources...), &v1alpha1.LbPoolMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LbPoolMember), err
}
