/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/dns/v1alpha1"
	scheme "kubeform.dev/provider-ibm-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReverseRecordsGetter has a method to return a ReverseRecordInterface.
// A group's client should implement this interface.
type ReverseRecordsGetter interface {
	ReverseRecords(namespace string) ReverseRecordInterface
}

// ReverseRecordInterface has methods to work with ReverseRecord resources.
type ReverseRecordInterface interface {
	Create(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.CreateOptions) (*v1alpha1.ReverseRecord, error)
	Update(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.UpdateOptions) (*v1alpha1.ReverseRecord, error)
	UpdateStatus(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.UpdateOptions) (*v1alpha1.ReverseRecord, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ReverseRecord, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ReverseRecordList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReverseRecord, err error)
	ReverseRecordExpansion
}

// reverseRecords implements ReverseRecordInterface
type reverseRecords struct {
	client rest.Interface
	ns     string
}

// newReverseRecords returns a ReverseRecords
func newReverseRecords(c *DnsV1alpha1Client, namespace string) *reverseRecords {
	return &reverseRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the reverseRecord, and returns the corresponding reverseRecord object, and an error if there is any.
func (c *reverseRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReverseRecord, err error) {
	result = &v1alpha1.ReverseRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reverserecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReverseRecords that match those selectors.
func (c *reverseRecords) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReverseRecordList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ReverseRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reverserecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested reverseRecords.
func (c *reverseRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("reverserecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a reverseRecord and creates it.  Returns the server's representation of the reverseRecord, and an error, if there is any.
func (c *reverseRecords) Create(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.CreateOptions) (result *v1alpha1.ReverseRecord, err error) {
	result = &v1alpha1.ReverseRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("reverserecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reverseRecord).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a reverseRecord and updates it. Returns the server's representation of the reverseRecord, and an error, if there is any.
func (c *reverseRecords) Update(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.UpdateOptions) (result *v1alpha1.ReverseRecord, err error) {
	result = &v1alpha1.ReverseRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reverserecords").
		Name(reverseRecord.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reverseRecord).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *reverseRecords) UpdateStatus(ctx context.Context, reverseRecord *v1alpha1.ReverseRecord, opts v1.UpdateOptions) (result *v1alpha1.ReverseRecord, err error) {
	result = &v1alpha1.ReverseRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reverserecords").
		Name(reverseRecord.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(reverseRecord).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the reverseRecord and deletes it. Returns an error if one occurs.
func (c *reverseRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reverserecords").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *reverseRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reverserecords").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched reverseRecord.
func (c *reverseRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReverseRecord, err error) {
	result = &v1alpha1.ReverseRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("reverserecords").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
