/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddonsListerExpansion allows custom methods to be added to
// AddonsLister.
type AddonsListerExpansion interface{}

// AddonsNamespaceListerExpansion allows custom methods to be added to
// AddonsNamespaceLister.
type AddonsNamespaceListerExpansion interface{}

// AlbListerExpansion allows custom methods to be added to
// AlbLister.
type AlbListerExpansion interface{}

// AlbNamespaceListerExpansion allows custom methods to be added to
// AlbNamespaceLister.
type AlbNamespaceListerExpansion interface{}

// AlbCertListerExpansion allows custom methods to be added to
// AlbCertLister.
type AlbCertListerExpansion interface{}

// AlbCertNamespaceListerExpansion allows custom methods to be added to
// AlbCertNamespaceLister.
type AlbCertNamespaceListerExpansion interface{}

// ApiKeyResetListerExpansion allows custom methods to be added to
// ApiKeyResetLister.
type ApiKeyResetListerExpansion interface{}

// ApiKeyResetNamespaceListerExpansion allows custom methods to be added to
// ApiKeyResetNamespaceLister.
type ApiKeyResetNamespaceListerExpansion interface{}

// BindServiceListerExpansion allows custom methods to be added to
// BindServiceLister.
type BindServiceListerExpansion interface{}

// BindServiceNamespaceListerExpansion allows custom methods to be added to
// BindServiceNamespaceLister.
type BindServiceNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// ClusterFeatureListerExpansion allows custom methods to be added to
// ClusterFeatureLister.
type ClusterFeatureListerExpansion interface{}

// ClusterFeatureNamespaceListerExpansion allows custom methods to be added to
// ClusterFeatureNamespaceLister.
type ClusterFeatureNamespaceListerExpansion interface{}

// VpcAlbListerExpansion allows custom methods to be added to
// VpcAlbLister.
type VpcAlbListerExpansion interface{}

// VpcAlbNamespaceListerExpansion allows custom methods to be added to
// VpcAlbNamespaceLister.
type VpcAlbNamespaceListerExpansion interface{}

// VpcClusterListerExpansion allows custom methods to be added to
// VpcClusterLister.
type VpcClusterListerExpansion interface{}

// VpcClusterNamespaceListerExpansion allows custom methods to be added to
// VpcClusterNamespaceLister.
type VpcClusterNamespaceListerExpansion interface{}

// VpcWorkerPoolListerExpansion allows custom methods to be added to
// VpcWorkerPoolLister.
type VpcWorkerPoolListerExpansion interface{}

// VpcWorkerPoolNamespaceListerExpansion allows custom methods to be added to
// VpcWorkerPoolNamespaceLister.
type VpcWorkerPoolNamespaceListerExpansion interface{}

// WorkerPoolListerExpansion allows custom methods to be added to
// WorkerPoolLister.
type WorkerPoolListerExpansion interface{}

// WorkerPoolNamespaceListerExpansion allows custom methods to be added to
// WorkerPoolNamespaceLister.
type WorkerPoolNamespaceListerExpansion interface{}

// WorkerPoolZoneAttachmentListerExpansion allows custom methods to be added to
// WorkerPoolZoneAttachmentLister.
type WorkerPoolZoneAttachmentListerExpansion interface{}

// WorkerPoolZoneAttachmentNamespaceListerExpansion allows custom methods to be added to
// WorkerPoolZoneAttachmentNamespaceLister.
type WorkerPoolZoneAttachmentNamespaceListerExpansion interface{}
