/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ibm-api/apis/storage/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEvaults implements EvaultInterface
type FakeEvaults struct {
	Fake *FakeStorageV1alpha1
	ns   string
}

var evaultsResource = schema.GroupVersionResource{Group: "storage.ibm.kubeform.com", Version: "v1alpha1", Resource: "evaults"}

var evaultsKind = schema.GroupVersionKind{Group: "storage.ibm.kubeform.com", Version: "v1alpha1", Kind: "Evault"}

// Get takes name of the evault, and returns the corresponding evault object, and an error if there is any.
func (c *FakeEvaults) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Evault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(evaultsResource, c.ns, name), &v1alpha1.Evault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Evault), err
}

// List takes label and field selectors, and returns the list of Evaults that match those selectors.
func (c *FakeEvaults) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EvaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(evaultsResource, evaultsKind, c.ns, opts), &v1alpha1.EvaultList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EvaultList{ListMeta: obj.(*v1alpha1.EvaultList).ListMeta}
	for _, item := range obj.(*v1alpha1.EvaultList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested evaults.
func (c *FakeEvaults) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(evaultsResource, c.ns, opts))

}

// Create takes the representation of a evault and creates it.  Returns the server's representation of the evault, and an error, if there is any.
func (c *FakeEvaults) Create(ctx context.Context, evault *v1alpha1.Evault, opts v1.CreateOptions) (result *v1alpha1.Evault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(evaultsResource, c.ns, evault), &v1alpha1.Evault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Evault), err
}

// Update takes the representation of a evault and updates it. Returns the server's representation of the evault, and an error, if there is any.
func (c *FakeEvaults) Update(ctx context.Context, evault *v1alpha1.Evault, opts v1.UpdateOptions) (result *v1alpha1.Evault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(evaultsResource, c.ns, evault), &v1alpha1.Evault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Evault), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEvaults) UpdateStatus(ctx context.Context, evault *v1alpha1.Evault, opts v1.UpdateOptions) (*v1alpha1.Evault, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(evaultsResource, "status", c.ns, evault), &v1alpha1.Evault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Evault), err
}

// Delete takes name of the evault and deletes it. Returns an error if one occurs.
func (c *FakeEvaults) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(evaultsResource, c.ns, name), &v1alpha1.Evault{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEvaults) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(evaultsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EvaultList{})
	return err
}

// Patch applies the patch and returns the patched evault.
func (c *FakeEvaults) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Evault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(evaultsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Evault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Evault), err
}
